/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.configuraciones.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.DateToStringConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.IntegerToStringConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.StringToBigDecimalConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.StringToIntegerConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.core.DateComboBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.SpinnerBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.TextFieldBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ButtonBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.CheckBoxBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ComboBoxBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.PasswordFieldBinding;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author CARLOS_CODESOFT
 */
public abstract class AsistenteConfiguracionRapidaPanel extends ControladorCodefacInterface {

    /**
     * Creates new form AsistenteConfiguracionRapidaPanel
     */
    public AsistenteConfiguracionRapidaPanel() {
        initComponents();
        //getTxtFirmaFechaEmision().set
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        tabVentana = new javax.swing.JTabbedPane();
        pnlEmpresaSucursal3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lblEspacio3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblRequisitosPrevios = new javax.swing.JLabel();
        pnlEmpresaSucursal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresaNombreComercial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmpresaAgenteRetencion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmpresaNombreLogo = new javax.swing.JTextField();
        chkEmpresaRegimenMicroempresa = new javax.swing.JCheckBox();
        chkEmpresaObligadoContabilidad = new javax.swing.JCheckBox();
        txtEmpresaFacebook = new javax.swing.JTextField();
        lblEspacio = new javax.swing.JLabel();
        btnEmpresaCargarLogo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSucursalTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmpresaInstagram = new javax.swing.JTextField();
        txtSucursalDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtWhatsapp = new javax.swing.JTextField();
        txtEmpresaRuc = new javax.swing.JTextField();
        txtEmpresaRazonSocial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSucursalCodigo = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        pnlEmpresaSucursal1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblEspacio1 = new javax.swing.JLabel();
        btnFirmaBuscar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtFirmaNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtCorreoUsuario = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPuntoEmision = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        txtFirmaFechaEmision = new org.jdesktop.swingx.JXDatePicker();
        jLabel26 = new javax.swing.JLabel();
        txtPuntoEmisionSecuencialFactura = new javax.swing.JSpinner();
        txtPuntoEmisionSecuencialNC = new javax.swing.JSpinner();
        txtCorreoPuerto = new javax.swing.JSpinner();
        txtFirmaDuracion = new javax.swing.JSpinner();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtCorreoSmtp = new javax.swing.JTextField();
        txtPuntoEmisionSecuencialRetenciones = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        txtFirmaContraseña = new javax.swing.JPasswordField();
        txtCorreoClave = new javax.swing.JPasswordField();
        btnVerificarDatosFirma = new javax.swing.JButton();
        btnVerificarCorreo = new javax.swing.JButton();
        lblAyudaCorreo = new javax.swing.JLabel();
        lblAyudaFirmaElectrónica = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        cmbModoFacturacion = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        pnlEmpresaSucursal2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblEspacio2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtUsuarioNick = new javax.swing.JTextField();
        lblLinkRegistro = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblEspacio123 = new javax.swing.JLabel();
        txtUsuarioRepetirClave = new javax.swing.JPasswordField();
        txtUsuarioClave = new javax.swing.JPasswordField();
        lblEspacio34959 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtLicenciaCorreo = new javax.swing.JTextField();
        txtLicenciaClave = new javax.swing.JPasswordField();
        btnVerificarLicencia = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnAtrasPantalla = new javax.swing.JButton();
        btnAvanzarPantalla = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        tabVentana.setEnabled(false);

        pnlEmpresaSucursal3.setLayout(new java.awt.GridBagLayout());

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Gracias por instalar Codefac, en este momento el asistente te guiará para que realices las configuraciones necesarias e inicies a usar el sistema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal3.add(jLabel32, gridBagConstraints);
        pnlEmpresaSucursal3.add(lblEspacio3, new java.awt.GridBagConstraints());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/codefac-logotipo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlEmpresaSucursal3.add(jLabel16, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel33.setText("Asistente de Configuración Rápida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlEmpresaSucursal3.add(jLabel33, gridBagConstraints);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/ejecutiva.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        pnlEmpresaSucursal3.add(jLabel19, gridBagConstraints);

        lblRequisitosPrevios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRequisitosPrevios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequisitosPrevios.setText("<html> \t<body> \t\t<center> \t\t\t<a href=\"www.google.com\"> \t\t\t\t<h3>Requisitos Previos</h3> \t\t\t</a> \t\t</center> \t\t<p>- Tener RUC y Permisos para facturación electrónica en el Sri</p> \t\t<p>- Firma Electrónica en formato p12</p> \t\t<p>- Correo Electrónico (preferencia GMAIL)</p> \t\t<p>- Cuenta creada en la página de CODEFAC</p> \t</body> </html>");
        lblRequisitosPrevios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal3.add(lblRequisitosPrevios, gridBagConstraints);

        tabVentana.addTab("Inicio", pnlEmpresaSucursal3);

        pnlEmpresaSucursal.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Datos de la empresa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nombre Comercial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaNombreComercial, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Facebook:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaAgenteRetencion, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("*Apellidos y Nombres | Razón Social:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel6, gridBagConstraints);

        txtEmpresaNombreLogo.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaNombreLogo, gridBagConstraints);

        chkEmpresaRegimenMicroempresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkEmpresaRegimenMicroempresa.setText("Régimen Microempresas");
        chkEmpresaRegimenMicroempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmpresaRegimenMicroempresaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(chkEmpresaRegimenMicroempresa, gridBagConstraints);

        chkEmpresaObligadoContabilidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkEmpresaObligadoContabilidad.setText("Obligado a llevar contabilidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(chkEmpresaObligadoContabilidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaFacebook, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlEmpresaSucursal.add(lblEspacio, gridBagConstraints);

        btnEmpresaCargarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(btnEmpresaCargarLogo, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Logo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtSucursalTelefono, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Instagram:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel9, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Agente de retención resolución:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaInstagram, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtSucursalDireccion, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Datos de la sucursal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel2, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Whatsapp:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel10, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Código Establecimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("*Ruc:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtWhatsapp, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaRuc, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtEmpresaRazonSocial, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(txtSucursalCodigo, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("*Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal.add(jLabel15, gridBagConstraints);

        tabVentana.addTab("Empresa Y Sucursal", pnlEmpresaSucursal);

        pnlEmpresaSucursal1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Puntos de Emisión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Secuencial Nota Crédito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel7, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Secuencial Factura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlEmpresaSucursal1.add(lblEspacio1, gridBagConstraints);

        btnFirmaBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(btnFirmaBuscar, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Secuencial Retenciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel18, gridBagConstraints);

        txtFirmaNombre.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtFirmaNombre, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Correo Electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel22, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Fecha de Emisión de la firma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel23, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Punto de Emisión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel24, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtCorreoUsuario, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Firma Archivo (P12):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel25, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtPuntoEmision, gridBagConstraints);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText("Duración Firma (Años):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel40, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtFirmaFechaEmision, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Facturación Electrónica Firma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel26, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtPuntoEmisionSecuencialFactura, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtPuntoEmisionSecuencialNC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtCorreoPuerto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtFirmaDuracion, gridBagConstraints);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel41.setText("Correo para enviar notificaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel41, gridBagConstraints);

        jLabel42.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel42.setText("Se recomienda utilizar un nuevo punto de emisión para usar la facturación electrónica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel42, gridBagConstraints);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel43.setText("Contraseña Correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel43, gridBagConstraints);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setText("Host (Smtp):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel44, gridBagConstraints);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 51, 51));
        jLabel45.setText("Modo Facturación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel45, gridBagConstraints);

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setText("Contraseña Firma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel46, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtCorreoSmtp, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtPuntoEmisionSecuencialRetenciones, gridBagConstraints);

        jLabel47.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel47.setText("El modo de facturación por defecto es PRUEBAS para que puedan realizar ajustes en el sistema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel47, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtFirmaContraseña, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(txtCorreoClave, gridBagConstraints);

        btnVerificarDatosFirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/FacturaCeleste.png"))); // NOI18N
        btnVerificarDatosFirma.setText("Verificar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(btnVerificarDatosFirma, gridBagConstraints);

        btnVerificarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/FacturaCeleste.png"))); // NOI18N
        btnVerificarCorreo.setText("Verificar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(btnVerificarCorreo, gridBagConstraints);

        lblAyudaCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/help-ico.png"))); // NOI18N
        lblAyudaCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlEmpresaSucursal1.add(lblAyudaCorreo, gridBagConstraints);

        lblAyudaFirmaElectrónica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/help-ico.png"))); // NOI18N
        lblAyudaFirmaElectrónica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlEmpresaSucursal1.add(lblAyudaFirmaElectrónica, gridBagConstraints);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel48.setText("Puerto (Smtp):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel48, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal1.add(cmbModoFacturacion, gridBagConstraints);

        jLabel51.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel51.setText("Los datos ingresados son de prueba , se recomiendo cambiar por un correo de su empresa de preferencia GMAIL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlEmpresaSucursal1.add(jLabel51, gridBagConstraints);

        tabVentana.addTab("Datos Adicionales", pnlEmpresaSucursal1);

        pnlEmpresaSucursal2.setLayout(new java.awt.GridBagLayout());

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Datos Licencia Codefac");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel27, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("*Repetir Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel28, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("*Clave: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel30, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlEmpresaSucursal2.add(lblEspacio2, gridBagConstraints);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setText("*Correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel37, gridBagConstraints);

        txtUsuarioNick.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(txtUsuarioNick, gridBagConstraints);

        lblLinkRegistro.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        lblLinkRegistro.setForeground(new java.awt.Color(0, 102, 153));
        lblLinkRegistro.setText("Página Codefac Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(lblLinkRegistro, gridBagConstraints);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("<html> \t<body> \t\t<center> \t\t\t<h3>Consideraciones Finales</h3> \t\t</center> \t\t<p>- Si no cuentas con toda la información puede cerrar el asistente y volver a acceder</p> \t\t<p>- Algunas funciones no están disponibles para los usuarios gratuitos</p> \t\t<p>- Finalmente presione el <b>botón de Terminar</b> y luego tiene que volver a ingresar con el usuario creado</p> \t</body> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel29, gridBagConstraints);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/cliente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        pnlEmpresaSucursal2.add(jLabel21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.6;
        pnlEmpresaSucursal2.add(lblEspacio123, gridBagConstraints);

        txtUsuarioRepetirClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(txtUsuarioRepetirClave, gridBagConstraints);

        txtUsuarioClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(txtUsuarioClave, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.6;
        pnlEmpresaSucursal2.add(lblEspacio34959, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setText("Usuario Nuevo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel31, gridBagConstraints);

        jLabel49.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        jLabel49.setText("Los datos ingresados en este momento son para poder acceder al sistema");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel49, gridBagConstraints);

        jLabel50.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        jLabel50.setText("Para activar el sistema debes tener registrada una cuenta en nuestra página web, o puedes hacerlo desde el siguiente link");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel50, gridBagConstraints);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setText("*Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel38, gridBagConstraints);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel39.setText("*Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(jLabel39, gridBagConstraints);

        txtLicenciaCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(txtLicenciaCorreo, gridBagConstraints);

        txtLicenciaClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(txtLicenciaClave, gridBagConstraints);

        btnVerificarLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/FacturaCeleste.png"))); // NOI18N
        btnVerificarLicencia.setText("Verificar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlEmpresaSucursal2.add(btnVerificarLicencia, gridBagConstraints);

        tabVentana.addTab("Usuario", pnlEmpresaSucursal2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(tabVentana, gridBagConstraints);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAtrasPantalla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAtrasPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/atras.png"))); // NOI18N
        btnAtrasPantalla.setText("Atras");
        btnAtrasPantalla.setFocusable(false);
        btnAtrasPantalla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtrasPantalla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAtrasPantalla);

        btnAvanzarPantalla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAvanzarPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/enviar.png"))); // NOI18N
        btnAvanzarPantalla.setText("Siguiente");
        btnAvanzarPantalla.setFocusable(false);
        btnAvanzarPantalla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAvanzarPantalla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAvanzarPantalla);

        btnTerminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/32Pixeles/visto.png"))); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.setFocusable(false);
        btnTerminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTerminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnTerminar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jToolBar1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEmpresaRegimenMicroempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmpresaRegimenMicroempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEmpresaRegimenMicroempresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasPantalla;
    private javax.swing.JButton btnAvanzarPantalla;
    private javax.swing.JButton btnEmpresaCargarLogo;
    private javax.swing.JButton btnFirmaBuscar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton btnVerificarCorreo;
    private javax.swing.JButton btnVerificarDatosFirma;
    private javax.swing.JButton btnVerificarLicencia;
    private javax.swing.JCheckBox chkEmpresaObligadoContabilidad;
    private javax.swing.JCheckBox chkEmpresaRegimenMicroempresa;
    private javax.swing.JComboBox<String> cmbModoFacturacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAyudaCorreo;
    private javax.swing.JLabel lblAyudaFirmaElectrónica;
    private javax.swing.JLabel lblEspacio;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio123;
    private javax.swing.JLabel lblEspacio2;
    private javax.swing.JLabel lblEspacio3;
    private javax.swing.JLabel lblEspacio34959;
    private javax.swing.JLabel lblLinkRegistro;
    private javax.swing.JLabel lblRequisitosPrevios;
    private javax.swing.JPanel pnlEmpresaSucursal;
    private javax.swing.JPanel pnlEmpresaSucursal1;
    private javax.swing.JPanel pnlEmpresaSucursal2;
    private javax.swing.JPanel pnlEmpresaSucursal3;
    private javax.swing.JTabbedPane tabVentana;
    private javax.swing.JPasswordField txtCorreoClave;
    private javax.swing.JSpinner txtCorreoPuerto;
    private javax.swing.JTextField txtCorreoSmtp;
    private javax.swing.JTextField txtCorreoUsuario;
    private javax.swing.JTextField txtEmpresaAgenteRetencion;
    private javax.swing.JTextField txtEmpresaFacebook;
    private javax.swing.JTextField txtEmpresaInstagram;
    private javax.swing.JTextField txtEmpresaNombreComercial;
    private javax.swing.JTextField txtEmpresaNombreLogo;
    private javax.swing.JTextField txtEmpresaRazonSocial;
    private javax.swing.JTextField txtEmpresaRuc;
    private javax.swing.JPasswordField txtFirmaContraseña;
    private javax.swing.JSpinner txtFirmaDuracion;
    private org.jdesktop.swingx.JXDatePicker txtFirmaFechaEmision;
    private javax.swing.JTextField txtFirmaNombre;
    private javax.swing.JPasswordField txtLicenciaClave;
    private javax.swing.JTextField txtLicenciaCorreo;
    private javax.swing.JSpinner txtPuntoEmision;
    private javax.swing.JSpinner txtPuntoEmisionSecuencialFactura;
    private javax.swing.JSpinner txtPuntoEmisionSecuencialNC;
    private javax.swing.JSpinner txtPuntoEmisionSecuencialRetenciones;
    private javax.swing.JSpinner txtSucursalCodigo;
    private javax.swing.JTextField txtSucursalDireccion;
    private javax.swing.JTextField txtSucursalTelefono;
    private javax.swing.JPasswordField txtUsuarioClave;
    private javax.swing.JTextField txtUsuarioNick;
    private javax.swing.JPasswordField txtUsuarioRepetirClave;
    private javax.swing.JTextField txtWhatsapp;
    // End of variables declaration//GEN-END:variables

    

    @ButtonBinding(actionListener = "controlador.listenerBtnBuscarLogoEmpresa")
    public JButton getBtnEmpresaCargarLogo() {
        return btnEmpresaCargarLogo;
    }

    public void setBtnEmpresaCargarLogo(JButton btnEmpresaCargarLogo) {
        this.btnEmpresaCargarLogo = btnEmpresaCargarLogo;
    }

    @CheckBoxBinding(value = "controlador.empresa.obligadoLlevarContabilidadBool")
    public JCheckBox getChkEmpresaObligadoContabilidad() {
        return chkEmpresaObligadoContabilidad;
    }

    public void setChkEmpresaObligadoContabilidad(JCheckBox chkEmpresaObligadoContabilidad) {
        this.chkEmpresaObligadoContabilidad = chkEmpresaObligadoContabilidad;
    }

    @CheckBoxBinding(value = "controlador.empresa.contribuyenteRegimenMicroempresasBool")
    public JCheckBox getChkEmpresaRegimenMicroempresa() {
        return chkEmpresaRegimenMicroempresa;
    }

    public void setChkEmpresaRegimenMicroempresa(JCheckBox chkEmpresaRegimenMicroempresa) {
        this.chkEmpresaRegimenMicroempresa = chkEmpresaRegimenMicroempresa;
    }

    public JTabbedPane getTabVentana() {
        return tabVentana;
    }

    public void setTabVentana(JTabbedPane tabVentana) {
        this.tabVentana = tabVentana;
    }

    @ButtonBinding(actionListener = "controlador.listenerBtnBuscarFirma")
    public JButton getBtnFirmaBuscar() {
        return btnFirmaBuscar;
    }

    public void setBtnFirmaBuscar(JButton btnFirmaBuscar) {
        this.btnFirmaBuscar = btnFirmaBuscar;
    }
    
    @PasswordFieldBinding(value = "controlador.correoClaveParametro.valor")
    public JPasswordField getTxtCorreoClave() {
        return txtCorreoClave;
    }

    public void setTxtCorreoClave(JPasswordField txtCorreoClave) {
        this.txtCorreoClave = txtCorreoClave;
    }

    @SpinnerBinding(value = "controlador.correoPuertoParametro.valor",converter = IntegerToStringConverter.class)
    public JSpinner getTxtCorreoPuerto() {
        return txtCorreoPuerto;
    }

    public void setTxtCorreoPuerto(JSpinner txtCorreoPuerto) {
        this.txtCorreoPuerto = txtCorreoPuerto;
    }

    @TextFieldBinding(value="controlador.correoHostSmtpParametro.valor")
    public JTextField getTxtCorreoSmtp() {
        return txtCorreoSmtp;
    }

    public void setTxtCorreoSmtp(JTextField txtCorreoSmtp) {
        this.txtCorreoSmtp = txtCorreoSmtp;
    }

    @TextFieldBinding(value = "controlador.correoUsuarioParametro.valor")
    public JTextField getTxtCorreoUsuario() {
        return txtCorreoUsuario;
    }

    public void setTxtCorreoUsuario(JTextField txtCorreoUsuario) {
        this.txtCorreoUsuario = txtCorreoUsuario;
    }

    @TextFieldBinding(value = "controlador.empresa.agenteRetencionResolucion")
    public JTextField getTxtEmpresaAgenteRetencion() {
        return txtEmpresaAgenteRetencion;
    }

    public void setTxtEmpresaAgenteRetencion(JTextField txtEmpresaAgenteRetencion) {
        this.txtEmpresaAgenteRetencion = txtEmpresaAgenteRetencion;
    }

    @TextFieldBinding(value = "controlador.empresa.facebook")
    public JTextField getTxtEmpresaFacebook() {
        return txtEmpresaFacebook;
    }
    
    public void setTxtEmpresaFacebook(JTextField txtEmpresaFacebook) {
        this.txtEmpresaFacebook = txtEmpresaFacebook;
    }

    @TextFieldBinding(value = "controlador.empresa.instagram")
    public JTextField getTxtEmpresaInstagram() {
        return txtEmpresaInstagram;
    }

    public void setTxtEmpresaInstagram(JTextField txtEmpresaInstagram) {
        this.txtEmpresaInstagram = txtEmpresaInstagram;
    }

    @TextFieldBinding(value = "controlador.empresa.nombreLegal")
    public JTextField getTxtEmpresaNombreComercial() {
        return txtEmpresaNombreComercial;
    }

    public void setTxtEmpresaNombreComercial(JTextField txtEmpresaNombreComercial) {
        this.txtEmpresaNombreComercial = txtEmpresaNombreComercial;
    }

    @TextFieldBinding(value = "controlador.empresa.imagenLogoPath")
    public JTextField getTxtEmpresaNombreLogo() {
        return txtEmpresaNombreLogo;
    }

    public void setTxtEmpresaNombreLogo(JTextField txtEmpresaNombreLogo) {
        this.txtEmpresaNombreLogo = txtEmpresaNombreLogo;
    }

    //@ValidacionCodefacAnotacion(requerido = true)
    @TextFieldBinding(value = "controlador.empresa.razonSocial")
    public JTextField getTxtEmpresaRazonSocial() {
        return txtEmpresaRazonSocial;
    }

    public void setTxtEmpresaRazonSocial(JTextField txtEmpresaRazonSocial) {
        this.txtEmpresaRazonSocial = txtEmpresaRazonSocial;
    }

    
    //@ValidacionCodefacAnotacion(requerido = true)
    @TextFieldBinding(value = "controlador.empresa.identificacion")
    public JTextField getTxtEmpresaRuc() {
        return txtEmpresaRuc;
    }

    public void setTxtEmpresaRuc(JTextField txtEmpresaRuc) {
        this.txtEmpresaRuc = txtEmpresaRuc;
    }

    @PasswordFieldBinding(value = "controlador.firmaClaveParametro.valor")
    public JPasswordField getTxtFirmaContraseña() {
        return txtFirmaContraseña;
    }

    public void setTxtFirmaContraseña(JPasswordField txtFirmaContraseña) {
        this.txtFirmaContraseña = txtFirmaContraseña;
    }

    @SpinnerBinding(value = "controlador.firmaDuracionParametro.valor",converter = IntegerToStringConverter.class)
    public JSpinner getTxtFirmaDuracion() {
        return txtFirmaDuracion;
    }

    public void setTxtFirmaDuracion(JSpinner txtFirmaDuracion) {
        this.txtFirmaDuracion = txtFirmaDuracion;
    }

    @DateComboBinding(value = "controlador.firmaFechaEmisionParametro.valor",converter =DateToStringConverter.class )
    public JXDatePicker getTxtFirmaFechaEmision() {
        return txtFirmaFechaEmision;
    }

    public void setTxtFirmaFechaEmision(JXDatePicker txtFirmaFechaEmision) {
        this.txtFirmaFechaEmision = txtFirmaFechaEmision;
    }

    @TextFieldBinding(value = "controlador.firmaArchivoParametro.valor")
    public JTextField getTxtFirmaNombre() {
        return txtFirmaNombre;
    }

    public void setTxtFirmaNombre(JTextField txtFirmaNombre) {
        this.txtFirmaNombre = txtFirmaNombre;
    }

    @SpinnerBinding(value = "controlador.puntoEmision.puntoEmision")
    public JSpinner getTxtPuntoEmision() {
        return txtPuntoEmision;
    }

    public void setTxtPuntoEmision(JSpinner txtPuntoEmision) {
        this.txtPuntoEmision = txtPuntoEmision;
    }

    @SpinnerBinding(value = "controlador.puntoEmision.secuencialFactura")
    public JSpinner getTxtPuntoEmisionSecuencialFactura() {
        return txtPuntoEmisionSecuencialFactura;
    }

    public void setTxtPuntoEmisionSecuencialFactura(JSpinner txtPuntoEmisionSecuencialFactura) {
        this.txtPuntoEmisionSecuencialFactura = txtPuntoEmisionSecuencialFactura;
    }

    @SpinnerBinding(value = "controlador.puntoEmision.secuencialNotaCredito")
    public JSpinner getTxtPuntoEmisionSecuencialNC() {
        return txtPuntoEmisionSecuencialNC;
    }

    public void setTxtPuntoEmisionSecuencialNC(JSpinner txtPuntoEmisionSecuencialNC) {
        this.txtPuntoEmisionSecuencialNC = txtPuntoEmisionSecuencialNC;
    }

    @SpinnerBinding(value = "controlador.puntoEmision.secuencialRetenciones")
    public JSpinner getTxtPuntoEmisionSecuencialRetenciones() {
        return txtPuntoEmisionSecuencialRetenciones;
    }

    public void setTxtPuntoEmisionSecuencialRetenciones(JSpinner txtPuntoEmisionSecuencialRetenciones) {
        this.txtPuntoEmisionSecuencialRetenciones = txtPuntoEmisionSecuencialRetenciones;
    }

    @SpinnerBinding(value = "controlador.sucursal.codigoSucursal")
    public JSpinner getTxtSucursalCodigo() {
        return txtSucursalCodigo;
    }

    public void setTxtSucursalCodigo(JSpinner txtSucursalCodigo) {
        this.txtSucursalCodigo = txtSucursalCodigo;
    }

    @TextFieldBinding(value = "controlador.sucursal.direcccion")
    public JTextField getTxtSucursalDireccion() {
        return txtSucursalDireccion;
    }

    public void setTxtSucursalDireccion(JTextField txtSucursalDireccion) {
        this.txtSucursalDireccion = txtSucursalDireccion;
    }

    @TextFieldBinding(value = "controlador.sucursal.telefono")
    public JTextField getTxtSucursalTelefono() {
        return txtSucursalTelefono;
    }

    public void setTxtSucursalTelefono(JTextField txtSucursalTelefono) {
        this.txtSucursalTelefono = txtSucursalTelefono;
    }

    @TextFieldBinding(value = "controlador.sucursal.celular")
    public JTextField getTxtWhatsapp() {
        return txtWhatsapp;
    }

    public void setTxtWhatsapp(JTextField txtWhatsapp) {
        this.txtWhatsapp = txtWhatsapp;
    }

    @ButtonBinding(actionListener = "controlador.listenerBtnAvanzarPantalla")
    public JButton getBtnAvanzarPantalla() {
        return btnAvanzarPantalla;
    }

    public void setBtnAvanzarPantalla(JButton btnAvanzarPantalla) {
        this.btnAvanzarPantalla = btnAvanzarPantalla;
    }

    @ButtonBinding(actionListener = "controlador.listenerBtnAtrasPantalla")
    public JButton getBtnAtrasPantalla() {
        return btnAtrasPantalla;
    }

    public void setBtnAtrasPantalla(JButton btnAtrasPantalla) {
        this.btnAtrasPantalla = btnAtrasPantalla;
    }

    @ButtonBinding(actionListener = "controlador.listenerBtnTerminar",habilitarBoton = "controlador.botonTerminarHabilitar" )
    public JButton getBtnTerminar() {
        return btnTerminar;
    }

    public void setBtnTerminar(JButton btnTerminar) {
        this.btnTerminar = btnTerminar;
    }

    //@ValidacionCodefacAnotacion(requerido = true)
    @TextFieldBinding(value = "controlador.usuario.nick")
    public JTextField getTxtUsuarioNick() {
        return txtUsuarioNick;
    }

    
    public void setTxtUsuarioNick(JTextField txtUsuarioNick) {
        this.txtUsuarioNick = txtUsuarioNick;
    }
    
    @TextFieldBinding(value = "controlador.usuario.clave")
    public JPasswordField getTxtUsuarioClave() {
        return txtUsuarioClave;
    }

    public void setTxtUsuarioClave(JPasswordField txtUsuarioClave) {
        this.txtUsuarioClave = txtUsuarioClave;
    }

    @TextFieldBinding(value = "controlador.usuario.repetirClave")
    public JPasswordField getTxtUsuarioRepetirClave() {
        return txtUsuarioRepetirClave;
    }

    public void setTxtUsuarioRepetirClave(JPasswordField txtUsuarioRepetirClave) {
        this.txtUsuarioRepetirClave = txtUsuarioRepetirClave;
    }

    @ButtonBinding(actionListener = "controlador.listenerVerificarDatosFirma")
    public JButton getBtnVerificarDatosFirma() {
        return btnVerificarDatosFirma;
    }

    public void setBtnVerificarDatosFirma(JButton btnVerificarDatosFirma) {
        this.btnVerificarDatosFirma = btnVerificarDatosFirma;
    }

    @ButtonBinding(actionListener = "controlador.listenerVerificarCorreo")
    public JButton getBtnVerificarCorreo() {
        return btnVerificarCorreo;
    }

    public void setBtnVerificarCorreo(JButton btnVerificarCorreo) {
        this.btnVerificarCorreo = btnVerificarCorreo;
    }

    @PasswordFieldBinding(value = "controlador.licenciaClave")
    public JPasswordField getTxtLicenciaClave() {
        return txtLicenciaClave;
    }

    public void setTxtLicenciaClave(JPasswordField txtLicenciaClave) {
        this.txtLicenciaClave = txtLicenciaClave;
    }

    @TextFieldBinding(value = "controlador.licenciaCorreo")
    public JTextField getTxtLicenciaCorreo() {
        return txtLicenciaCorreo;
    }

    public void setTxtLicenciaCorreo(JTextField txtLicenciaCorreo) {
        this.txtLicenciaCorreo = txtLicenciaCorreo;
    }

    @ButtonBinding(actionListener = "controlador.listenerVerificarLicencia")
    public JButton getBtnVerificarLicencia() {
        return btnVerificarLicencia;
    }
    

    public void setBtnVerificarLicencia(JButton btnVerificarLicencia) {
        this.btnVerificarLicencia = btnVerificarLicencia;
    }

    @ComboBoxBinding(source = "controlador.modoFacturacionList" ,valueSelect = "controlador.modoFacturacionParametro.valor")
    public JComboBox<String> getCmbModoFacturacion() {
        return cmbModoFacturacion;
    }

    public void setCmbModoFacturacion(JComboBox<String> cmbModoFacturacion) {
        this.cmbModoFacturacion = cmbModoFacturacion;
    }
    
    

    public JLabel getLblAyudaCorreo() {
        return lblAyudaCorreo;
    }

    public void setLblAyudaCorreo(JLabel lblAyudaCorreo) {
        this.lblAyudaCorreo = lblAyudaCorreo;
    }

    public JLabel getLblLinkRegistro() {
        return lblLinkRegistro;
    }

    public void setLblLinkRegistro(JLabel lblLinkRegistro) {
        this.lblLinkRegistro = lblLinkRegistro;
    }

    public JLabel getLblAyudaFirmaElectrónica() {
        return lblAyudaFirmaElectrónica;
    }

    public void setLblAyudaFirmaElectrónica(JLabel lblAyudaFirmaElectrónica) {
        this.lblAyudaFirmaElectrónica = lblAyudaFirmaElectrónica;
    }

    public JLabel getLblRequisitosPrevios() {
        return lblRequisitosPrevios;
    }

    public void setLblRequisitosPrevios(JLabel lblRequisitosPrevios) {
        this.lblRequisitosPrevios = lblRequisitosPrevios;
    }

    
    
    
    
}
