/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.configuraciones.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vista.factura.FacturaModelControlador.FormatoReporteEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.ComprobanteEntity;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.ComprobanteEntity.ComprobanteEnumEstado;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.SriFormaPago;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.SriRetencionIva;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.SriRetencionRenta;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.ConfiguracionImpresoraEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.DocumentoEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.EnumSiNo;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.FormatoHojaEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.TipoDocumentoEnum;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author
 */
public abstract class ConfiguracionDefectoPanel extends ControladorCodefacInterface {

    /**
     * Creates new form ConfiguracionDefectoPanel
     */
    public ConfiguracionDefectoPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        lblEspacio1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoDocumentoCompra = new javax.swing.JComboBox<>();
        lblEspacio3 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtNotaVentaInternaAlias = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrdenTrabajoReporte = new javax.swing.JTextArea();
        lblEspacioBlanco2 = new javax.swing.JLabel();
        lblEspacioBlanco = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbFormatoHojas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbActivarModuloCartera = new javax.swing.JComboBox<>();
        lblEspacio6 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cmbCreditoDefectoFacturas = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblEspacioVertical = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbActivarComprobanteVenta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbCargarProductoIvaFactura = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        chkImpresoraTickets = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtVariableGeneralComprobantes = new javax.swing.JTextField();
        lblEspacioBlanco123 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbEditarPrecioUnitFactura = new javax.swing.JComboBox<>();
        cmbEditarDescripcionFactura = new javax.swing.JComboBox<>();
        cmbEditarDescuentoFactura = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbActivarNotaVenta = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbDatoAdicionalRideRazoSocialEmpledo = new javax.swing.JComboBox<>();
        cmbDatoAdicionalRideDireccionEmpledo = new javax.swing.JComboBox<>();
        cmbDatoAdicionalRidePuntoEmisionEmpleado = new javax.swing.JComboBox<>();
        cmbDatoAdicionalRideRucEmpledo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmbConfiguracionImpresora = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cmbDocumentoDefectoVistaFactura = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        cmbReporteDefectoVenta = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cmbDatoAdicionalRideCodigoPersonalizado = new javax.swing.JComboBox<>();
        cmbDatoAdicionalRideReferenciaDireccion = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        txtNumeroMaximoDetalleFactura = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cmbMostrarTituloFactFisica = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtLeyendaFirmaFactura1 = new javax.swing.JTextField();
        txtLeyendaFirmaFactura3 = new javax.swing.JTextField();
        txtLeyendaFirmaFactura2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtNumeroDecimalesRide = new javax.swing.JSpinner();
        jLabel49 = new javax.swing.JLabel();
        cmbNotaVentaInternaIva = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        cmbProformaFacturarVariasVeces = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        cmbImprimirCodigoInternoProducto = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblEspacioVertical1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbActivarReporteSimpleGuiaRemision = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtMotivoTrasladoGuiaRemision = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        cmbModoFacturasGuiaRemision = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        cmbDocumentoGuiaRemisionDefecto = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        cmbFormaPagoDefecto = new javax.swing.JComboBox<>();
        lblEspacio12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbRetencionIva = new javax.swing.JComboBox<>();
        lblEspacio42 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbRetencionRenta = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        cmbHabilitarRetencionesEnCompras = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigoHtml = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPanelVistaPrevia = new javax.swing.JEditorPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cmbFacturarInventarioNegativo = new javax.swing.JComboBox<>();
        lblEspacioBlanco12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbConstruirEnsamblesFacturar = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        txtNumeroDecimalesProducto = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cmbDatosCompartidosEmpresas = new javax.swing.JComboBox<>();
        lblEspacio637 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtDiasAlertaPago = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        jComboFiltrarFacturaPorUsuario = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        cmbFiltroRapidoBusqueda = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configuraciones por Defecto");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Tipo Documento Defecto Factura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbTipoDocumento, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(lblEspacio1, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Nota de Venta Interna (Alias):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbTipoDocumentoCompra, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(lblEspacio3, gridBagConstraints);

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setText("Tipo Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel52, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtNotaVentaInternaAlias, gridBagConstraints);

        jTabbedPane1.addTab("Documentos", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Detalles Reporte Ordenes de Trabajo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        txtOrdenTrabajoReporte.setColumns(20);
        txtOrdenTrabajoReporte.setRows(5);
        jScrollPane1.setViewportView(txtOrdenTrabajoReporte);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(lblEspacioBlanco2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(lblEspacioBlanco, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Formato Reportes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(cmbFormatoHojas, gridBagConstraints);

        jTabbedPane1.addTab("Ordenes Trabajo", jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Activar Módulo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel4, gridBagConstraints);

        cmbActivarModuloCartera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(cmbActivarModuloCartera, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(lblEspacio6, gridBagConstraints);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel36.setText("Crédito Por Defecto Facturas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel36, gridBagConstraints);

        cmbCreditoDefectoFacturas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(cmbCreditoDefectoFacturas, gridBagConstraints);

        jTabbedPane1.addTab("Cartera", jPanel3);

        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(lblEspacioVertical, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Cargar forma de cargar productos con iva:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel5, gridBagConstraints);

        cmbActivarComprobanteVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbActivarComprobanteVenta, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Imprimir Codigo Interno Producto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel7, gridBagConstraints);

        cmbCargarProductoIvaFactura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbCargarProductoIvaFactura, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Razón Social Empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel4.add(chkImpresoraTickets, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("TIpo Reporte Defecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtVariableGeneralComprobantes, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.1;
        jPanel4.add(lblEspacioBlanco123, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Editar Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Leyenda Firma 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Mostrar titulos facturas Físicas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel18, gridBagConstraints);

        cmbEditarPrecioUnitFactura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbEditarPrecioUnitFactura, gridBagConstraints);

        cmbEditarDescripcionFactura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbEditarDescripcionFactura, gridBagConstraints);

        cmbEditarDescuentoFactura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbEditarDescuentoFactura, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Activar Reporte Comprobante Venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel19, gridBagConstraints);

        cmbActivarNotaVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbActivarNotaVenta, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Parametros Facturas Físicas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel22, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Permitir facturar varias veces la misma proforma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel23, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Referencia Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel24, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Ruc Empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel25, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Dirección Empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel26, gridBagConstraints);

        cmbDatoAdicionalRideRazoSocialEmpledo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDatoAdicionalRideRazoSocialEmpledo, gridBagConstraints);

        cmbDatoAdicionalRideDireccionEmpledo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDatoAdicionalRideDireccionEmpledo, gridBagConstraints);

        cmbDatoAdicionalRidePuntoEmisionEmpleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDatoAdicionalRidePuntoEmisionEmpleado, gridBagConstraints);

        cmbDatoAdicionalRideRucEmpledo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDatoAdicionalRideRucEmpledo, gridBagConstraints);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Datos Adicionales Imprimir en el Ride");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel29, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Variable General Comprobantes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel30, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbConfiguracionImpresora, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Activar Documento Nota de  Venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel33, gridBagConstraints);

        cmbDocumentoDefectoVistaFactura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDocumentoDefectoVistaFactura, gridBagConstraints);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("Impresora con tickets:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel34, gridBagConstraints);

        cmbReporteDefectoVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbReporteDefectoVenta, gridBagConstraints);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel37.setText("Número decimales Ride:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel37, gridBagConstraints);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("Punto de Emisión Facturado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel38, gridBagConstraints);

        cmbDatoAdicionalRideCodigoPersonalizado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDatoAdicionalRideCodigoPersonalizado, gridBagConstraints);

        cmbDatoAdicionalRideReferenciaDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbDatoAdicionalRideReferenciaDireccion, gridBagConstraints);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setText("Documento por Defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel39, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtNumeroMaximoDetalleFactura, gridBagConstraints);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel41.setText("Leyendas Firmas Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel41, gridBagConstraints);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel42.setText("Número Máximo de Detalles Factura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel42, gridBagConstraints);

        cmbMostrarTituloFactFisica.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbMostrarTituloFactFisica, gridBagConstraints);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel43.setText("Proformas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel43, gridBagConstraints);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setText("Editar Descuento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel44, gridBagConstraints);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel45.setText("Leyenda Firma 3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel45, gridBagConstraints);

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setText("Leyenda Firma 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel46, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtLeyendaFirmaFactura1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtLeyendaFirmaFactura3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtLeyendaFirmaFactura2, gridBagConstraints);

        jLabel47.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel47.setText("Código Personalizado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel47, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtNumeroDecimalesRide, gridBagConstraints);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setText("Configuración impresora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel49, gridBagConstraints);

        cmbNotaVentaInternaIva.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbNotaVentaInternaIva, gridBagConstraints);

        jLabel50.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel50.setText("Habilitar Campos Facturación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel50, gridBagConstraints);

        jLabel51.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel51.setText("Editar Precio Unitario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel51, gridBagConstraints);

        cmbProformaFacturarVariasVeces.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbProformaFacturarVariasVeces, gridBagConstraints);

        jLabel55.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel55.setText("Nota de Venta Interna con iva:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel55, gridBagConstraints);

        cmbImprimirCodigoInternoProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbImprimirCodigoInternoProducto, gridBagConstraints);

        jTabbedPane1.addTab("Facturas", jPanel4);

        jPanel5.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(lblEspacioVertical1, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Modo factura para guias de remisión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel6, gridBagConstraints);

        cmbActivarReporteSimpleGuiaRemision.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(cmbActivarReporteSimpleGuiaRemision, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Documento Guía Remisión Defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtMotivoTrasladoGuiaRemision, gridBagConstraints);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText("Motivo Traslado Por Defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel40, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(cmbModoFacturasGuiaRemision, gridBagConstraints);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel48.setText("Reporte Simplificado Guia Retención:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel48, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(cmbDocumentoGuiaRemisionDefecto, gridBagConstraints);

        jTabbedPane1.addTab("Transporte", jPanel5);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("Forma de pago por defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel10.add(jLabel31, gridBagConstraints);

        cmbFormaPagoDefecto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel10.add(cmbFormaPagoDefecto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel10.add(lblEspacio12, gridBagConstraints);

        jTabbedPane1.addTab("Clientes", jPanel10);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Habilitar retenciones en compras:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(cmbRetencionIva, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel6.add(lblEspacio42, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Valor por defecto retención iva:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(cmbRetencionRenta, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Valor por defecto retención renta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jLabel32, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(cmbHabilitarRetencionesEnCompras, gridBagConstraints);

        jTabbedPane1.addTab("Retenciones", jPanel6);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        txtCodigoHtml.setColumns(20);
        txtCodigoHtml.setRows(5);
        jScrollPane2.setViewportView(txtCodigoHtml);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(jScrollPane2, gridBagConstraints);

        jScrollPane3.setViewportView(jEditorPanelVistaPrevia);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(jScrollPane3, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Código HTML");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel7.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Vista Previa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel7.add(jLabel15, gridBagConstraints);

        jTabbedPane1.addTab("Comprobantes Electrónicos", jPanel7);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Decimales Cantidad Producto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jLabel20, gridBagConstraints);

        cmbFacturarInventarioNegativo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(cmbFacturarInventarioNegativo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel8.add(lblEspacioBlanco12, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Facturar con inventario negativo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jLabel21, gridBagConstraints);

        cmbConstruirEnsamblesFacturar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(cmbConstruirEnsamblesFacturar, gridBagConstraints);

        jLabel53.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel53.setText("Construir ensambles al facturar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jLabel53, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(txtNumeroDecimalesProducto, gridBagConstraints);

        jTabbedPane1.addTab("Inventario", jPanel8);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Número de días para alertar deudas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(jLabel27, gridBagConstraints);

        cmbDatosCompartidosEmpresas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(cmbDatosCompartidosEmpresas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(lblEspacio637, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Datos Compartidos Entre Empresas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(jLabel28, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(txtDiasAlertaPago, gridBagConstraints);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("Filtro Rapido Dialogo de Busqueda:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(jLabel35, gridBagConstraints);

        jComboFiltrarFacturaPorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFiltrarFacturaPorUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(jComboFiltrarFacturaPorUsuario, gridBagConstraints);

        jLabel54.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel54.setText("Filtrar por usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(jLabel54, gridBagConstraints);

        cmbFiltroRapidoBusqueda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel9.add(cmbFiltroRapidoBusqueda, gridBagConstraints);

        jTabbedPane1.addTab("General", jPanel9);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboFiltrarFacturaPorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFiltrarFacturaPorUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFiltrarFacturaPorUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkImpresoraTickets;
    private javax.swing.JComboBox<EnumSiNo> cmbActivarComprobanteVenta;
    private javax.swing.JComboBox<EnumSiNo> cmbActivarModuloCartera;
    private javax.swing.JComboBox<EnumSiNo> cmbActivarNotaVenta;
    private javax.swing.JComboBox<EnumSiNo> cmbActivarReporteSimpleGuiaRemision;
    private javax.swing.JComboBox<EnumSiNo> cmbCargarProductoIvaFactura;
    private javax.swing.JComboBox<ConfiguracionImpresoraEnum> cmbConfiguracionImpresora;
    private javax.swing.JComboBox<EnumSiNo> cmbConstruirEnsamblesFacturar;
    private javax.swing.JComboBox<EnumSiNo> cmbCreditoDefectoFacturas;
    private javax.swing.JComboBox<EnumSiNo> cmbDatoAdicionalRideCodigoPersonalizado;
    private javax.swing.JComboBox<EnumSiNo> cmbDatoAdicionalRideDireccionEmpledo;
    private javax.swing.JComboBox<EnumSiNo> cmbDatoAdicionalRidePuntoEmisionEmpleado;
    private javax.swing.JComboBox<EnumSiNo> cmbDatoAdicionalRideRazoSocialEmpledo;
    private javax.swing.JComboBox<EnumSiNo> cmbDatoAdicionalRideReferenciaDireccion;
    private javax.swing.JComboBox<EnumSiNo> cmbDatoAdicionalRideRucEmpledo;
    private javax.swing.JComboBox<EnumSiNo> cmbDatosCompartidosEmpresas;
    private javax.swing.JComboBox<DocumentoEnum> cmbDocumentoDefectoVistaFactura;
    private javax.swing.JComboBox<DocumentoEnum> cmbDocumentoGuiaRemisionDefecto;
    private javax.swing.JComboBox<EnumSiNo> cmbEditarDescripcionFactura;
    private javax.swing.JComboBox<EnumSiNo> cmbEditarDescuentoFactura;
    private javax.swing.JComboBox<EnumSiNo> cmbEditarPrecioUnitFactura;
    private javax.swing.JComboBox<EnumSiNo> cmbFacturarInventarioNegativo;
    private javax.swing.JComboBox<EnumSiNo> cmbFiltroRapidoBusqueda;
    private javax.swing.JComboBox<SriFormaPago> cmbFormaPagoDefecto;
    private javax.swing.JComboBox<FormatoHojaEnum> cmbFormatoHojas;
    private javax.swing.JComboBox<EnumSiNo> cmbHabilitarRetencionesEnCompras;
    private javax.swing.JComboBox<EnumSiNo> cmbImprimirCodigoInternoProducto;
    private javax.swing.JComboBox<ComprobanteEntity.ComprobanteEnumEstado> cmbModoFacturasGuiaRemision;
    private javax.swing.JComboBox<EnumSiNo> cmbMostrarTituloFactFisica;
    private javax.swing.JComboBox<EnumSiNo> cmbNotaVentaInternaIva;
    private javax.swing.JComboBox<EnumSiNo> cmbProformaFacturarVariasVeces;
    private javax.swing.JComboBox<FormatoReporteEnum> cmbReporteDefectoVenta;
    private javax.swing.JComboBox<SriRetencionIva> cmbRetencionIva;
    private javax.swing.JComboBox<SriRetencionRenta> cmbRetencionRenta;
    private javax.swing.JComboBox<TipoDocumentoEnum> cmbTipoDocumento;
    private javax.swing.JComboBox<TipoDocumentoEnum> cmbTipoDocumentoCompra;
    private javax.swing.JComboBox<EnumSiNo> jComboFiltrarFacturaPorUsuario;
    private javax.swing.JEditorPane jEditorPanelVistaPrevia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio12;
    private javax.swing.JLabel lblEspacio3;
    private javax.swing.JLabel lblEspacio42;
    private javax.swing.JLabel lblEspacio6;
    private javax.swing.JLabel lblEspacio637;
    private javax.swing.JLabel lblEspacioBlanco;
    private javax.swing.JLabel lblEspacioBlanco12;
    private javax.swing.JLabel lblEspacioBlanco123;
    private javax.swing.JLabel lblEspacioBlanco2;
    private javax.swing.JLabel lblEspacioVertical;
    private javax.swing.JLabel lblEspacioVertical1;
    private javax.swing.JTextArea txtCodigoHtml;
    private javax.swing.JSpinner txtDiasAlertaPago;
    private javax.swing.JTextField txtLeyendaFirmaFactura1;
    private javax.swing.JTextField txtLeyendaFirmaFactura2;
    private javax.swing.JTextField txtLeyendaFirmaFactura3;
    private javax.swing.JTextField txtMotivoTrasladoGuiaRemision;
    private javax.swing.JTextField txtNotaVentaInternaAlias;
    private javax.swing.JSpinner txtNumeroDecimalesProducto;
    private javax.swing.JSpinner txtNumeroDecimalesRide;
    private javax.swing.JTextField txtNumeroMaximoDetalleFactura;
    private javax.swing.JTextArea txtOrdenTrabajoReporte;
    private javax.swing.JTextField txtVariableGeneralComprobantes;
    // End of variables declaration//GEN-END:variables

    public JComboBox<TipoDocumentoEnum> getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public void setCmbTipoDocumento(JComboBox<TipoDocumentoEnum> cmbTipoDocumento) {
        this.cmbTipoDocumento = cmbTipoDocumento;
    }

    public JComboBox<TipoDocumentoEnum> getCmbTipoDocumentoCompra() {
        return cmbTipoDocumentoCompra;
    }

    public void setCmbTipoDocumentoCompra(JComboBox<TipoDocumentoEnum> cmbTipoDocumentoCompra) {
        this.cmbTipoDocumentoCompra = cmbTipoDocumentoCompra;
    }

    public JTextArea getTxtOrdenTrabajoReporte() {
        return txtOrdenTrabajoReporte;
    }

    public void setTxtOrdenTrabajoReporte(JTextArea txtOrdenTrabajoReporte) {
        this.txtOrdenTrabajoReporte = txtOrdenTrabajoReporte;
    }

    public JComboBox<FormatoHojaEnum> getCmbFormatoHojas() {
        return cmbFormatoHojas;
    }

    public void setCmbFormatoHojas(JComboBox<FormatoHojaEnum> cmbFormatoHojas) {
        this.cmbFormatoHojas = cmbFormatoHojas;
    }

    public JComboBox<EnumSiNo> getCmbActivarModuloCartera() {
        return cmbActivarModuloCartera;
    }

    public void setCmbActivarModuloCartera(JComboBox<EnumSiNo> cmbActivarModuloCartera) {
        this.cmbActivarModuloCartera = cmbActivarModuloCartera;
    }

    public JComboBox<EnumSiNo> getCmbActivarComprobanteVenta() {
        return cmbActivarComprobanteVenta;
    }

    public void setCmbActivarComprobanteVenta(JComboBox<EnumSiNo> cmbActivarComprobanteVenta) {
        this.cmbActivarComprobanteVenta = cmbActivarComprobanteVenta;
    }

    public JComboBox<EnumSiNo> getCmbActivarReporteSimpleGuiaRemision() {
        return cmbActivarReporteSimpleGuiaRemision;
    }

    public void setCmbActivarReporteSimpleGuiaRemision(JComboBox<EnumSiNo> cmbActivarReporteSimpleGuiaRemision) {
        this.cmbActivarReporteSimpleGuiaRemision = cmbActivarReporteSimpleGuiaRemision;
    }

    public JComboBox<EnumSiNo> getCmbCargarProductoIvaFactura() {
        return cmbCargarProductoIvaFactura;
    }

    public JTextField getTxtMotivoTrasladoGuiaRemision() {
        return txtMotivoTrasladoGuiaRemision;
    }

    public JComboBox<SriRetencionIva> getCmbRetencionIva() {
        return cmbRetencionIva;
    }

    public void setCmbRetencionIva(JComboBox<SriRetencionIva> cmbRetencionIva) {
        this.cmbRetencionIva = cmbRetencionIva;
    }

    public JComboBox<SriRetencionRenta> getCmbRetencionRenta() {
        return cmbRetencionRenta;
    }

    public void setCmbRetencionRenta(JComboBox<SriRetencionRenta> cmbRetencionRenta) {
        this.cmbRetencionRenta = cmbRetencionRenta;
    }

    public JCheckBox getChkImpresoraTickets() {
        return chkImpresoraTickets;
    }

    public JTextField getTxtVariableGeneralComprobantes() {
        return txtVariableGeneralComprobantes;
    }

    public JEditorPane getjEditorPanelVistaPrevia() {
        return jEditorPanelVistaPrevia;
    }

    public JTextArea getTxtCodigoHtml() {
        return txtCodigoHtml;
    }

    public JComboBox<EnumSiNo> getCmbEditarDescripcionFactura() {
        return cmbEditarDescripcionFactura;
    }

    public JComboBox<EnumSiNo> getCmbEditarDescuentoFactura() {
        return cmbEditarDescuentoFactura;
    }

    public JComboBox<EnumSiNo> getCmbEditarPrecioUnitFactura() {
        return cmbEditarPrecioUnitFactura;
    }

    public JComboBox<EnumSiNo> getCmbActivarNotaVenta() {
        return cmbActivarNotaVenta;
    }

    public void setCmbActivarNotaVenta(JComboBox<EnumSiNo> cmbActivarNotaVenta) {
        this.cmbActivarNotaVenta = cmbActivarNotaVenta;
    }

    public JComboBox<EnumSiNo> getCmbFacturarInventarioNegativo() {
        return cmbFacturarInventarioNegativo;
    }

    public void setCmbFacturarInventarioNegativo(JComboBox<EnumSiNo> cmbFacturarInventarioNegativo) {
        this.cmbFacturarInventarioNegativo = cmbFacturarInventarioNegativo;
    }

    public JComboBox<EnumSiNo> getCmbConstruirEnsamblesFacturar() {
        return cmbConstruirEnsamblesFacturar;
    }

    public void setCmbConstruirEnsamblesFacturar(JComboBox<EnumSiNo> cmbConstruirEnsamblesFacturar) {
        this.cmbConstruirEnsamblesFacturar = cmbConstruirEnsamblesFacturar;
    }

    public JComboBox<EnumSiNo> getCmbDatoAdicionalRideDireccionEmpledo() {
        return cmbDatoAdicionalRideDireccionEmpledo;
    }

    public void setCmbDatoAdicionalRideDireccionEmpledo(JComboBox<EnumSiNo> cmbDatoAdicionalRideDireccionEmpledo) {
        this.cmbDatoAdicionalRideDireccionEmpledo = cmbDatoAdicionalRideDireccionEmpledo;
    }

    public JComboBox<EnumSiNo> getCmbDatoAdicionalRidePuntoEmisionEmpleado() {
        return cmbDatoAdicionalRidePuntoEmisionEmpleado;
    }

    public void setCmbDatoAdicionalRidePuntoEmisionEmpleado(JComboBox<EnumSiNo> cmbDatoAdicionalRidePuntoEmisionEmpleado) {
        this.cmbDatoAdicionalRidePuntoEmisionEmpleado = cmbDatoAdicionalRidePuntoEmisionEmpleado;
    }

    public JComboBox<EnumSiNo> getCmbDatoAdicionalRideRazoSocialEmpledo() {
        return cmbDatoAdicionalRideRazoSocialEmpledo;
    }

    public void setCmbDatoAdicionalRideRazoSocialEmpledo(JComboBox<EnumSiNo> cmbDatoAdicionalRideRazoSocialEmpledo) {
        this.cmbDatoAdicionalRideRazoSocialEmpledo = cmbDatoAdicionalRideRazoSocialEmpledo;
    }

    public JComboBox<EnumSiNo> getCmbDatoAdicionalRideRucEmpledo() {
        return cmbDatoAdicionalRideRucEmpledo;
    }

    public void setCmbDatoAdicionalRideRucEmpledo(JComboBox<EnumSiNo> cmbDatoAdicionalRideRucEmpledo) {
        this.cmbDatoAdicionalRideRucEmpledo = cmbDatoAdicionalRideRucEmpledo;
    }

    public JComboBox<EnumSiNo> getCmbDatosCompartidosEmpresas() {
        return cmbDatosCompartidosEmpresas;
    }

    public void setCmbDatosCompartidosEmpresas(JComboBox<EnumSiNo> cmbDatosCompartidosEmpresas) {
        this.cmbDatosCompartidosEmpresas = cmbDatosCompartidosEmpresas;
    }

    public JSpinner getTxtDiasAlertaPago() {
        return txtDiasAlertaPago;
    }

    public void setTxtDiasAlertaPago(JSpinner txtDiasAlertaPago) {
        this.txtDiasAlertaPago = txtDiasAlertaPago;
    }

    public JComboBox<ConfiguracionImpresoraEnum> getCmbConfiguracionImpresora() {
        return cmbConfiguracionImpresora;
    }

    public void setCmbConfiguracionImpresora(JComboBox<ConfiguracionImpresoraEnum> cmbConfiguracionImpresora) {
        this.cmbConfiguracionImpresora = cmbConfiguracionImpresora;
    }

    public JComboBox<SriFormaPago> getCmbFormaPagoDefecto() {
        return cmbFormaPagoDefecto;
    }

    public void setCmbFormaPagoDefecto(JComboBox<SriFormaPago> cmbFormaPagoDefecto) {
        this.cmbFormaPagoDefecto = cmbFormaPagoDefecto;
    }

    public JComboBox<EnumSiNo> getCmbHabilitarRetencionesEnCompras() {
        return cmbHabilitarRetencionesEnCompras;
    }

    public JComboBox<DocumentoEnum> getCmbDocumentoDefectoVistaFactura() {
        return cmbDocumentoDefectoVistaFactura;
    }

    public JComboBox<EnumSiNo> getjComboFiltrarFacturaPorUsuario() {
        return jComboFiltrarFacturaPorUsuario;
    }

    public void setjComboFiltrarFacturaPorUsuario(JComboBox<EnumSiNo> jComboFiltrarFacturaPorUsuario) {
        this.jComboFiltrarFacturaPorUsuario = jComboFiltrarFacturaPorUsuario;
    }

    public JComboBox<FormatoReporteEnum> getCmbReporteDefectoVenta() {
        return cmbReporteDefectoVenta;
    }

    public void setCmbReporteDefectoVenta(JComboBox<FormatoReporteEnum> cmbReporteDefectoVenta) {
        this.cmbReporteDefectoVenta = cmbReporteDefectoVenta;
    }

    public JComboBox<EnumSiNo> getCmbCreditoDefectoFacturas() {
        return cmbCreditoDefectoFacturas;
    }

    public void setCmbCreditoDefectoFacturas(JComboBox<EnumSiNo> cmbCreditoDefectoFacturas) {
        this.cmbCreditoDefectoFacturas = cmbCreditoDefectoFacturas;
    }

    public JComboBox<EnumSiNo> getCmbDatoAdicionalRideCodigoPersonalizado() {
        return cmbDatoAdicionalRideCodigoPersonalizado;
    }

    public void setCmbDatoAdicionalRideCodigoPersonalizado(JComboBox<EnumSiNo> cmbDatoAdicionalRideCodigoPersonalizado) {
        this.cmbDatoAdicionalRideCodigoPersonalizado = cmbDatoAdicionalRideCodigoPersonalizado;
    }

    public JComboBox<EnumSiNo> getCmbDatoAdicionalRideReferenciaDireccion() {
        return cmbDatoAdicionalRideReferenciaDireccion;
    }

    public void setCmbDatoAdicionalRideReferenciaDireccion(JComboBox<EnumSiNo> cmbDatoAdicionalRideReferenciaDireccion) {
        this.cmbDatoAdicionalRideReferenciaDireccion = cmbDatoAdicionalRideReferenciaDireccion;
    }

    public JTextField getTxtNumeroMaximoDetalleFactura() {
        return txtNumeroMaximoDetalleFactura;
    }

    public void setTxtNumeroMaximoDetalleFactura(JTextField txtNumeroMaximoDetalleFactura) {
        this.txtNumeroMaximoDetalleFactura = txtNumeroMaximoDetalleFactura;
    }

    public JComboBox<ComprobanteEnumEstado> getCmbModoFacturasGuiaRemision() {
        return cmbModoFacturasGuiaRemision;
    }

    public void setCmbModoFacturasGuiaRemision(JComboBox<ComprobanteEnumEstado> cmbModoFacturasGuiaRemision) {
        this.cmbModoFacturasGuiaRemision = cmbModoFacturasGuiaRemision;
    }

    public JComboBox<EnumSiNo> getCmbMostrarTituloFactFisica() {
        return cmbMostrarTituloFactFisica;
    }

    public void setCmbMostrarTituloFactFisica(JComboBox<EnumSiNo> cmbMostrarTituloFactFisica) {
        this.cmbMostrarTituloFactFisica = cmbMostrarTituloFactFisica;
    }

    public JTextField getTxtLeyendaFirmaFactura1() {
        return txtLeyendaFirmaFactura1;
    }

    public void setTxtLeyendaFirmaFactura1(JTextField txtLeyendaFirmaFactura1) {
        this.txtLeyendaFirmaFactura1 = txtLeyendaFirmaFactura1;
    }

    public JTextField getTxtLeyendaFirmaFactura2() {
        return txtLeyendaFirmaFactura2;
    }

    public void setTxtLeyendaFirmaFactura2(JTextField txtLeyendaFirmaFactura2) {
        this.txtLeyendaFirmaFactura2 = txtLeyendaFirmaFactura2;
    }

    public JTextField getTxtLeyendaFirmaFactura3() {
        return txtLeyendaFirmaFactura3;
    }

    public void setTxtLeyendaFirmaFactura3(JTextField txtLeyendaFirmaFactura3) {
        this.txtLeyendaFirmaFactura3 = txtLeyendaFirmaFactura3;
    }

    public JSpinner getTxtNumeroDecimalesRide() {
        return txtNumeroDecimalesRide;
    }

    public void setTxtNumeroDecimalesRide(JSpinner txtNumeroDecimalesRide) {
        this.txtNumeroDecimalesRide = txtNumeroDecimalesRide;
    }

    public JComboBox<DocumentoEnum> getCmbDocumentoGuiaRemisionDefecto() {
        return cmbDocumentoGuiaRemisionDefecto;
    }

    public void setCmbDocumentoGuiaRemisionDefecto(JComboBox<DocumentoEnum> cmbDocumentoGuiaRemisionDefecto) {
        this.cmbDocumentoGuiaRemisionDefecto = cmbDocumentoGuiaRemisionDefecto;
    }

    public JComboBox<EnumSiNo> getCmbNotaVentaInternaIva() {
        return cmbNotaVentaInternaIva;
    }

    public void setCmbNotaVentaInternaIva(JComboBox<EnumSiNo> cmbNotaVentaInternaIva) {
        this.cmbNotaVentaInternaIva = cmbNotaVentaInternaIva;
    }

    public JComboBox<EnumSiNo> getCmbProformaFacturarVariasVeces() {
        return cmbProformaFacturarVariasVeces;
    }

    public void setCmbProformaFacturarVariasVeces(JComboBox<EnumSiNo> cmbProformaFacturarVariasVeces) {
        this.cmbProformaFacturarVariasVeces = cmbProformaFacturarVariasVeces;
    }

    public JTextField getTxtNotaVentaInternaAlias() {
        return txtNotaVentaInternaAlias;
    }

    public void setTxtNotaVentaInternaAlias(JTextField txtNotaVentaInternaAlias) {
        this.txtNotaVentaInternaAlias = txtNotaVentaInternaAlias;
    }

    public JSpinner getTxtNumeroDecimalesProducto() {
        return txtNumeroDecimalesProducto;
    }

    public void setTxtNumeroDecimalesProducto(JSpinner txtNumeroDecimalesProducto) {
        this.txtNumeroDecimalesProducto = txtNumeroDecimalesProducto;
    }

    public JComboBox<EnumSiNo> getCmbFiltroRapidoBusqueda() {
        return cmbFiltroRapidoBusqueda;
    }

    public void setCmbFiltroRapidoBusqueda(JComboBox<EnumSiNo> cmbFiltroRapidoBusqueda) {
        this.cmbFiltroRapidoBusqueda = cmbFiltroRapidoBusqueda;
    }

    public JComboBox<EnumSiNo> getCmbImprimirCodigoInternoProducto() {
        return cmbImprimirCodigoInternoProducto;
    }

    public void setCmbImprimirCodigoInternoProducto(JComboBox<EnumSiNo> cmbImprimirCodigoInternoProducto) {
        this.cmbImprimirCodigoInternoProducto = cmbImprimirCodigoInternoProducto;
    }

    
    
    
    
   
}
