/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.configuraciones.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.EnumSiNoToStringConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.IntegerToStringConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.core.SpinnerBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ComboBoxBinding;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.EnumSiNo;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author CodesoftDesarrollo 1
 */
public abstract class RespaldarInformacionPanel extends ControladorCodefacInterface
{

    /**
     * Creates new form RespaldarInformacion
     */
    public RespaldarInformacionPanel() {
        initComponents();
    }
    
    public JButton getBtnRespaldar() {
        return btnRespaldar;
    }

    public void setBtnRespaldar(JButton btnRespaldar) {
        this.btnRespaldar = btnRespaldar;
    }

    public JButton getBtnGuardarLocalizacion() {
        return btnGuardarLocalizacion;
    }

    public void setBtnGuardarLocalizacion(JButton btnGuardarLocalizacion) {
        this.btnGuardarLocalizacion = btnGuardarLocalizacion;
    }

    public JTextField getTxtUbicacionRespaldo() {
        return txtUbicacionRespaldo;
    }

    public void setTxtUbicacionRespaldo(JTextField txtUbicacionRespaldo) {
        this.txtUbicacionRespaldo = txtUbicacionRespaldo;
    }

    /*public JButton getBtnRespaldarCorreo() {
        return btnRespaldarCorreo;
    }

    public void setBtnRespaldarCorreo(JButton btnRespaldarCorreo) {
        this.btnRespaldarCorreo = btnRespaldarCorreo;
    }*/

    public JCheckBox getChkEnviarCorreo() {
        return chkEnviarCorreo;
    }

    public void setChkEnviarCorreo(JCheckBox chkEnviarCorreo) {
        this.chkEnviarCorreo = chkEnviarCorreo;
    }

    @ComboBoxBinding(source ="listEnumSiNo" ,valueSelect = "parametroRespaldarSalir.valor",converter = EnumSiNoToStringConverter.class)
    public JComboBox<EnumSiNo> getCmbRespaldarAlSalir() {
        return cmbRespaldarAlSalir;
    }

    public void setCmbRespaldarAlSalir(JComboBox<EnumSiNo> cmbRespaldarAlSalir) {
        this.cmbRespaldarAlSalir = cmbRespaldarAlSalir;
    }

    
    @SpinnerBinding(value = "parametroHoraProgramada.valor",converter = IntegerToStringConverter.class)
    public JSpinner getSpnHoraProgramada() {
        return spnHoraProgramada;
    }

    public void setSpnHoraProgramada(JSpinner spnHoraProgramada) {
        this.spnHoraProgramada = spnHoraProgramada;
    }

    public JButton getBtnEnviarBDCorreoPersonalizado() {
        return btnEnviarBDCorreoPersonalizado;
    }

    public void setBtnEnviarBDCorreoPersonalizado(JButton btnEnviarBDCorreoPersonalizado) {
        this.btnEnviarBDCorreoPersonalizado = btnEnviarBDCorreoPersonalizado;
    }

    public JTextField getTxtCorreoPersonalizado() {
        return txtCorreoPersonalizado;
    }

    public void setTxtCorreoPersonalizado(JTextField txtCorreoPersonalizado) {
        this.txtCorreoPersonalizado = txtCorreoPersonalizado;
    }
    
     

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnRespaldar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarLocalizacion = new javax.swing.JButton();
        txtUbicacionRespaldo = new javax.swing.JTextField();
        chkEnviarCorreo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRespaldarAlSalir = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        spnHoraProgramada = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtCorreoPersonalizado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEnviarBDCorreoPersonalizado = new javax.swing.JButton();
        lblEspacio123 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Respaldar BD");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnRespaldar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnRespaldar.setText("Respaldar Base de Datos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnRespaldar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Enviar Base de Datos a un correo personalizado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        btnGuardarLocalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar-ico.png"))); // NOI18N
        btnGuardarLocalizacion.setText("Guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        getContentPane().add(btnGuardarLocalizacion, gridBagConstraints);

        txtUbicacionRespaldo.setEditable(false);
        txtUbicacionRespaldo.setText("                                   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtUbicacionRespaldo, gridBagConstraints);

        chkEnviarCorreo.setText("Enviar al Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(chkEnviarCorreo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Respaldo Hora Programada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Seleccionar ubicación para respaldos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(cmbRespaldarAlSalir, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("correo electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(spnHoraProgramada, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Configuración Respaldos Automáticos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        txtCorreoPersonalizado.setText("info@codesoft-ec.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtCorreoPersonalizado, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Respaldar al Salir:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel6, gridBagConstraints);

        btnEnviarBDCorreoPersonalizado.setText("Enviar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(btnEnviarBDCorreoPersonalizado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(lblEspacio123, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarBDCorreoPersonalizado;
    private javax.swing.JButton btnGuardarLocalizacion;
    private javax.swing.JButton btnRespaldar;
    private javax.swing.JCheckBox chkEnviarCorreo;
    private javax.swing.JComboBox<EnumSiNo> cmbRespaldarAlSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEspacio123;
    private javax.swing.JSpinner spnHoraProgramada;
    private javax.swing.JTextField txtCorreoPersonalizado;
    private javax.swing.JTextField txtUbicacionRespaldo;
    // End of variables declaration//GEN-END:variables
}
