/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.main.panel;

import javax.swing.JButton;

/**
 *
 * @author
 */
public class ModoAplicativoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ModoAplicativoDialog
     */
    public ModoAplicativoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIniciarServidor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIniciarClienteServidor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnIniciarCliente = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnIniciarModoPrueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/codefac-nombre.PNG"))); // NOI18N
        jLabel4.setText("  Por favor seleccione el modo de ejecucion:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/servidor.png"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("<html> <p align=\"justify\">Se ejecuta como servidor en la maquina<br> y permite que otros usuario se conecten<br> este modo es óptimo cuando gran cantidad<br> de usuarios van a usar el sistema<br> <b>Disponible solo para la versión de pago</b></p> </html> \t");
        jPanel4.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        btnIniciarServidor.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarServidor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnIniciarServidor.setForeground(new java.awt.Color(0, 102, 51));
        btnIniciarServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/login.png"))); // NOI18N
        btnIniciarServidor.setText(" Iniciar Modo Servidor");
        jPanel4.add(btnIniciarServidor, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servidor y Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/clienteServidor.png"))); // NOI18N
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("<html> <p align=\"justify\"> Se ejecuta como servidor y cliente en <br> la misma máquina , ideal si se quiere<br> usar el sistema en una sola computadora<br>  <b>Si se requiere usar más de 1 usuario</b><br> <b>tiene que tener la version de pago</b> </p> </html> ");
        jPanel5.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        btnIniciarClienteServidor.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarClienteServidor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnIniciarClienteServidor.setForeground(new java.awt.Color(0, 102, 153));
        btnIniciarClienteServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/login.png"))); // NOI18N
        btnIniciarClienteServidor.setText(" Iniciar Cliente Servidor");
        jPanel5.add(btnIniciarClienteServidor, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/cliente.png"))); // NOI18N
        jPanel6.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("<html> <p align=\"justify\"> Esta versión solo se debe usar si se <br> tiene alguna otra versión de codefac<br> en modo servidor <br>  <b>El número de clientes disponibles</b><br> <b>depende de la versión contratada</b> </p> </html> ");
        jPanel6.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        btnIniciarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnIniciarCliente.setForeground(new java.awt.Color(204, 51, 0));
        btnIniciarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/login.png"))); // NOI18N
        btnIniciarCliente.setText(" Iniciar Modo Cliente");
        jPanel6.add(btnIniciarCliente, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modo Prueba", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel7.setName(""); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/pruebas.png"))); // NOI18N
        jPanel7.add(jLabel8, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("<html> <p align=\"justify\"> Versión de prueba del sistema Codefac <br> con datos e información configurados <br> para que el usuario pueda revisar <br> el funcionamiento del sistema. <br>  <b>Usuario: prueba y clave : 1234</b></p> </html>");
        jPanel7.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        btnIniciarModoPrueba.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarModoPrueba.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnIniciarModoPrueba.setForeground(new java.awt.Color(0, 102, 102));
        btnIniciarModoPrueba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/login.png"))); // NOI18N
        btnIniciarModoPrueba.setText(" Iniciar Modo Prueba");
        jPanel7.add(btnIniciarModoPrueba, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel7);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoAplicativoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoAplicativoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoAplicativoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoAplicativoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModoAplicativoDialog dialog = new ModoAplicativoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarCliente;
    private javax.swing.JButton btnIniciarClienteServidor;
    private javax.swing.JButton btnIniciarModoPrueba;
    private javax.swing.JButton btnIniciarServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnIniciarCliente() {
        return btnIniciarCliente;
    }

    public void setBtnIniciarCliente(JButton btnIniciarCliente) {
        this.btnIniciarCliente = btnIniciarCliente;
    }

    public JButton getBtnIniciarClienteServidor() {
        return btnIniciarClienteServidor;
    }

    public void setBtnIniciarClienteServidor(JButton btnIniciarClienteServidor) {
        this.btnIniciarClienteServidor = btnIniciarClienteServidor;
    }

    public JButton getBtnIniciarServidor() {
        return btnIniciarServidor;
    }

    public void setBtnIniciarServidor(JButton btnIniciarServidor) {
        this.btnIniciarServidor = btnIniciarServidor;
    }

    public JButton getBtnIniciarModoPrueba() {
        return btnIniciarModoPrueba;
    }
    
    

    
}
