/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.main.panel;

import ec.com.codesoft.codefaclite.main.model.ObjetoEscritorioAbstract;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author
 */
public abstract class WidgetNotificacionesCodefac extends ObjetoEscritorioAbstract {

    public WidgetNotificacionesCodefac(JDesktopPane parentPanel) {
        super(parentPanel);
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitulo = new javax.swing.JPanel();
        lblNotificaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotificaciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnActualizarNotificaciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setBackground(new java.awt.Color(40, 161, 207));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 51));
        lblTitulo.setLayout(new javax.swing.BoxLayout(lblTitulo, javax.swing.BoxLayout.LINE_AXIS));

        lblNotificaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNotificaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblNotificaciones.setText("Notificaciones Codefac");
        lblTitulo.add(lblNotificaciones);

        add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(tblNotificaciones);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnActualizarNotificaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnActualizarNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/FacturaCeleste.png"))); // NOI18N
        btnActualizarNotificaciones.setText("Actualizar Notificaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(btnActualizarNotificaciones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jLabel2, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarNotificaciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNotificaciones;
    private javax.swing.JPanel lblTitulo;
    private javax.swing.JTable tblNotificaciones;
    // End of variables declaration//GEN-END:variables

    public JTable getTblNotificaciones() {
        return tblNotificaciones;
    }

    public JButton getBtnActualizarNotificaciones() {
        return btnActualizarNotificaciones;
    }

    public JLabel getLblNotificaciones() {
        return lblNotificaciones;
    }
    
    

    
}
