/*AUMENTAR TAMANIO DE LOS CAMPOS DEL DECIMAL EN LA BASE DE DATOS*/
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ALTER DESCUENTO_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ALTER DESCUENTO_IVA_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ALTER SUBTOTAL_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ALTER SUBTOTAL_IVA_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ALTER IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ALTER TOTAL SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ALTER PRECIO_UNITARIO SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ALTER DESCUENTO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ALTER VALOR_RETENCION_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ALTER VALOR_RETENCION_RENTA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ALTER IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ALTER TOTAL SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ALTER IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ALTER TOTAL SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ALTER DESCUENTO_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ALTER DESCUENTO_IVA_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ALTER SUBTOTAL_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ALTER SUBTOTAL_IVA_CERO SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ALTER PRECIO_UNITARIO SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ALTER DESCUENTO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ALTER TOTAL SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ALTER IVA SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ALTER DESCUENTO_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ALTER DESCUENTO_IVA_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ALTER SUBTOTAL_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ALTER SUBTOTAL_IVA_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ALTER IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ALTER TOTAL SET DATA TYPE decimal(13,2);


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ALTER PRECIO_UNITARIO SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ALTER DESCUENTO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ALTER VALOR_ICE SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ALTER IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ALTER TOTAL SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_FORMA_PAGO ALTER TOTAL SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE IMPUESTO_DETALLE ALTER PORCENTAJE SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX ALTER PRECIO_PROMEDIO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX ALTER PRECIO_ULTIMO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX ALTER PRECIO_TOTAL SET DATA TYPE decimal(13,2);


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX_DETALLE ALTER PRECIO_UNITARIO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX_DETALLE ALTER PRECIO_TOTAL SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBROS_NIVEL ALTER VALOR SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_ESTUDIANTE ALTER VALOR SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_ESTUDIANTE ALTER SALDO SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_PLANTILLA ALTER VALOR SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA ALTER TOTAL SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA ALTER SALDO SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_DETALLE ALTER TOTAL SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_DETALLE ALTER SALDO SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_CRUCE ALTER VALOR SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER SUBTOTAL_SIN_IMPUESTOS SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER SUBTOTAL_DOCE SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER SUBTOTAL_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER VALOR_IVA_DOCE SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER VALOR_IVA_CERO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER TOTAL SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER DESCUENTO_IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ALTER DESCUENTO_IVA_CERO SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ALTER PRECIO_UNITARIO SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ALTER DESCUENTO SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ALTER IVA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ALTER TOTAL SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO ALTER VALOR_UNITARIO SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO ALTER PRECIO_DISTRIBUIDOR SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO ALTER PRECIO_TARJETA SET DATA TYPE decimal(13,3);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO_PROVEEDOR ALTER COSTO_ACTUAL SET DATA TYPE decimal(13,3);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE ALTER BASE_IMPONIBLE SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE ALTER PORCENTAJE_RETENER SET DATA TYPE decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE ALTER VALOR_RETENIDO SET DATA TYPE decimal(13,3);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ALTER DESCUENTO_COMPRA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ALTER DESCUENTO_VENTA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ALTER TOTAL_COMPRA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ALTER TOTAL_VENTA SET DATA TYPE decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ALTER PRECIO_COMPRA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ALTER DESCUENTO_COMPRA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ALTER PRECIO_VENTA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ALTER DESCUENTO_VENTA SET DATA TYPE decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ALTER CANTIDAD SET DATA TYPE decimal(13,2);