/* 
 * Actualizat los tipos de identificacion de la tabla de cliente
 */
/**
 * Author:  Carlos
 * Created: 24/07/2018
 */
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET IDENTIFICACION='9999999999999',RAZON_SOCIAL='Consumidor Final',NOMBRE_LEGAL='Consumidor Final',NOMBRES='Consumidor',APELLIDOS='Final',TIPO_OPERADOR='A' WHERE IDENTIFICACION='9999999999' or IDENTIFICACION='9999999999999' ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='R' WHERE LENGTH(IDENTIFICACION)=13;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='C' WHERE LENGTH(IDENTIFICACION)=10;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE CLIENTE SET TIPO_IDENTIFICACION='F' WHERE IDENTIFICACION='9999999999999';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='R' WHERE TIPO_IDENTIFICACION='RUC';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='C' WHERE TIPO_IDENTIFICACION='CEDULA';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='F' WHERE TIPO_IDENTIFICACION='CONSUMIDOR FINAL';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.5.6)*/
UPDATE SRI_IDENTIFICACION SET TIPO_IDENTIFICACION_LETRA='P' WHERE TIPO_IDENTIFICACION='PASAPORTE / IDENTIFICACION TRIBUTARIA DEL EXTERIOR';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.1)*/
ALTER TABLE EMPRESA ALTER RAZON_SOCIAL SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.1)*/
ALTER TABLE EMPRESA ALTER NOMBRE_LEGAL SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.1)*/
ALTER TABLE EMPRESA ALTER DIRECCION SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.3)*/
UPDATE RUBROS_NIVEL  SET ESTADO='A' ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.4)*/
UPDATE CLIENTE SET ESTADO='A' WHERE ESTADO IS NULL; /* Actualizacion con algunos clientes que se migraron sin estado especial para MyGoldenWorld*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.5)*/
DELETE FROM RUBRO_PLANTILLA_ESTUDIANTE  WHERE ESTUDIANTE_INSCRITO_ID IN (SELECT EI.ID FROM RUBRO_PLANTILLA_ESTUDIANTE PE,ESTUDIANTE_INSCRITO EI WHERE PE.ESTUDIANTE_INSCRITO_ID=EI.ID AND EI.ESTADO='E');/*Eliminar datos erroneos creados en las plantillas mensuales con estudiantes_inscritos eliminados*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Efectivo' WHERE CODIGO='01';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Compensación' WHERE CODIGO='15';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Tarjeta débito' WHERE CODIGO='16';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Dinero electrónico' WHERE CODIGO='17';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Tarjeta prepago' WHERE CODIGO='18';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Tarjeta crédito' WHERE CODIGO='19';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Otros' WHERE CODIGO='20';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE SRI_FORMA_PAGO SET ALIAS='Endoso títulos' WHERE CODIGO='21';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.6)*/
UPDATE RUBROS_NIVEL SET ESTADO='A' WHERE ESTADO IS NULL;/*Actualizando rubros del nivel que se crearon desde la plantilla y se estaban generando sin estado*/
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.7)*/
UPDATE RUBRO_PLANTILLA SET ESTADO='A' WHERE ESTADO IS NULL;/*Actualizar con el estado activo a todos los rubros de la plantilla creados*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.7)*/
CREATE FUNCTION TEXTO_ESTANDAR(texto VARCHAR(5000)) RETURNS VARCHAR(5000) 
    PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA 
    EXTERNAL NAME 'ec.com.codesoft.codefaclite.utilidades.varios.UtilidadesDerby.normalizarTextoDerby'; /*Agregar funcion para normalizar los texto y poder hacer busquedas sin importar acentos*/

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
ALTER TABLE SRI_RETENCION_RENTA ALTER NOMBRE SET DATA TYPE VARCHAR(256);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'304','SERVICIOS DONDE PREDOMINA EL INTELECTO NO RELACIONADOS CON EL TITULO',8.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'307','SERVICIOS DONDE PREDOMINA MANO DE OBRA',2.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'308','UTILIZACION O APROVECHAMIENTO DE LA IMAGEN O RENOMBRE',2.0000,'2009-03-20 00:00:00','2015-02-28 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'309','SERVICIOS PRETADOS POR MEDIOS DE COMUNICACION Y AGENCIAS DE PUBLICRETENCION_IDAD',1.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'310','SERVICIOS DE TRANSPORTE PRIVADO DE PASAJEROS O SERVICIO PÚBLICO O PRIVADO DE CARGA',1.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'312','TRANSFERENCIA DE BIENES MUEBLES DE NATURALEZA CORPORAL',1.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'319','ARRENDAMIENTO MERCANTIL',1.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'320','POR ARRENDAMIENTO DE BIENES INMUEBLES',8.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'322','SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)',1.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'323','RENDIMIENTOS FINANCIEROS',2.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'332','PAGOS DE BIENES O SERVICIOS NO SUJETOS A RETENCION',0.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'340','OTRAS RETENCIONES APLICABLES EL 1%',1.0000,'2009-03-20 00:00:00','2015-02-28 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'344','OTRAS RETENCIONES APLICABLES EL 2%',2.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'342','OTRAS RETENCIONES APLICABLES EL 8%',8.0000,'2009-03-20 00:00:00','2015-02-28 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'421','PAGOS AL EXTERIOR SIN CONVENIO DE DOBLE TRIBUTACIÓN',25.0000,'2009-03-20 00:00:00','2016-11-01 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'427','PAGOS AL EXTERIOR NO SUJETOS A RETENCIÓN',0.0000,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'303','HONORARIOS PROFESIONALES Y DEMAS PAGOS POR SERVICIOS RELACIONADOS CON EL TITULO PROFESIONAL',10.0000,'2010-06-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'343','APLICABLE A LA TARIFA DE IMPUESTO A LA RENTA PREVISTA PARA SOCIEDADES',22.0000,'2013-01-01 00:00:00','2015-02-28 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'343B','POR ACTIVRETENCION_IDADES DE CONSTRUCCION DE OBRA MATERIAL INMUEBLE, URBANIZACION, LOTIZACION O ACTIVRETENCION_IDADES SIMILARES',1.0000,'2015-03-04 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'304A','COMISIONES Y DEMAS PAGOS POR SERVICIOS PREDOMINA EL INTELECTO NO RELACIONADOS CON EL TITULO PROFESIONAL',8.0000,'2015-03-01 00:00:00','2016-10-31 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'304B','PAGOS A NOTARIOS Y REGISTRADORES DE LA PROPIEDAD Y MERCANTIL POR SUS ACTIVRETENCION_IDADES EJERCRETENCION_IDAS COMO TALES',8.0000,'2015-03-01 00:00:00','2016-10-31 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'304C','PAGOS A DEPORTISTAS, ENTRENADORES, ARBITROS, MIEMBROS DEL CUERPO TECNICO PRO SUS ACTIVRETENCION_IDADES EJERCRETENCION_IDAS COMO TALES',8.0000,'2015-03-01 00:00:00','2016-10-31 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'304D','PAGOS A ARTISTAS POR SUS ACTIVRETENCION_IDADES EJERCRETENCION_IDAS COMO TALES',8.0000,'2015-03-01 00:00:00','2016-10-31 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'308','UTILIZARION O APROVECHAMIENTO DE LA IMAGEN O RENOMBRE',10.0000,'2015-03-01 00:00:00','2016-10-31 00:00:00');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'311','POR PAGOS A TRAVES DE LIQURETENCION_IDACION DE COMPRA (NIVEL CULTURAL O RUSTICRETENCION_IDAD)',2.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'314A','REGALIAS POR NOMBRE DE FRANQUICIAS DE ACUERDO A LA LEY DE PROPIEDAD INTELECTUAL PAGO A PERSONAS NATURALES',8.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'314B','CANONES, DERECHOS DE AUTOR, MARCAS, PATENTES Y SIMILARES DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL PAGO A PERSONAS NATURALES',8.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'314C','REGALIAS POR NOMBRE DE FRANQUICIAS DE ACUERDO A LA LEY DE PROPIEDAD INTELECTUAL PAGO A SOCIEDADES',8.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'314D','CANONES, DERECHOS DE AUTOR, MARCAS, PATENTES Y SIMILARES DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL PAGO A SOCIEDADES',8.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'343A','POR ENERGIA ELECTRICA',1.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'344A','PAGO LOCAL TARJETA DE CREDITO REPORTADA POR LA EMISORA DE TARJETA DE CREDITO, SOLO RECAP',2.0000,'2015-03-01 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.8)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'308','UTILIZACION O APROVECHAMIENTO DE LA IMAGEN O RENOMBRE ',10.0000,'2015-03-01 00:00:00',NULL);


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9)*/
INSERT INTO SRI_RETENCION_IVA (RETENCION_ID,NOMBRE, CODIGO_SRI,PORCENTAJE,DESCRIPCION,FECHA_INICIO) VALUES (2,'NO APLICA' , '0' ,0,'NO APLICA','01/01/2000');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.2)*/
UPDATE BODEGA SET ESTADO='A' WHERE ESTADO='a';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.3)*/
UPDATE CLIENTE SET RAZON_SOCIAL= APELLIDOS || ' ' || NOMBRES  WHERE LENGTH (IDENTIFICACION)=10;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.3)*/
UPDATE CLIENTE SET ESTADO='A'  WHERE ESTADO IS NULL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
INSERT INTO PERMISO_VENTANA(PERFIL_ID,NOMBRE_CLASE,PERMISO_GRABAR,PERMISO_ELIMINAR,PERMISO_IMPRIMIR,PERMISO_EDITAR,PERMISO_BUSCAR) VALUES(1,'PVOR','s','s','s','s','s');


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.6)*/
INSERT INTO 
SUCURSAL (EMPRESA_ID,NOMBRE,TIPO,ESTADO,TELEFONO,DIRECCION,EMAIL,COD_SUCURSAL,CELULAR) 
VALUES 
((SELECT ID FROM EMPRESA),'MATRIZ','m','A',(SELECT TELEFONOS FROM EMPRESA),(SELECT DIRECCION FROM EMPRESA),'',(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='establecimiento'),(SELECT CELULAR FROM EMPRESA));


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.6)*/
INSERT INTO PUNTO_EMISION(SUCURSAL_ID,DESCRIPCION,PUNTO_EMISION,TIPO_FACTURACION,ESTADO,
SECUENCIAL_FACTURA,
SECUENCIAL_NOTA_CREDITO,
SECUENCIAL_NOTA_DEBITO,
SECUENCIAL_GUIA_REMISION,
SECUENCIAL_RETENCIONES,
SECUENCIAL_NOTA_VENTA)
VALUES
(1,'punto_emision',(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='punto_emision'),
'e',
'A',
(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='secuencial_factura'),
(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='secuencial_nota_credito'),
(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='secuencial_nota_debito'),
(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='secuencial_guia_remision'),
(SELECT CAST(VALOR AS BIGINT) FROM PARAMETRO WHERE NOMBRE='secuencial_retencion'),
1
);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE FACTURA ADD TIPO_IDENTIFICACION_CODIGO_SRI varchar(3);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.8)*/
UPDATE RUBRO_ESTUDIANTE SET ESTADO='E' WHERE VALOR=0;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.8)*/
INSERT INTO PERMISO_VENTANA(PERFIL_ID,NOMBRE_CLASE,PERMISO_GRABAR,PERMISO_ELIMINAR,PERMISO_IMPRIMIR,PERMISO_EDITAR,PERMISO_BUSCAR) VALUES(1,'SUCU','s','s','s','s','s');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.8)*/
INSERT INTO PERMISO_VENTANA(PERFIL_ID,NOMBRE_CLASE,PERMISO_GRABAR,PERMISO_ELIMINAR,PERMISO_IMPRIMIR,PERMISO_EDITAR,PERMISO_BUSCAR) VALUES(1,'PUVE','s','s','s','s','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.8,MOSTRAR_ERROR=SI)*/
ALTER TABLE DESTINATARIO_GUIA_REMISION ADD IDENTIFICACION varchar(32);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.9,MOSTRAR_ERROR=SI)*/
INSERT INTO PARAMETRO (NOMBRE,VALOR) VALUES('smtp_host','');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.9,MOSTRAR_ERROR=SI)*/
INSERT INTO PARAMETRO (NOMBRE,VALOR) VALUES('smtp_port','587');


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
UPDATE PRODUCTO SET NEW_COLUMN=VALOR_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO DROP COLUMN VALOR_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
RENAME COLUMN PRODUCTO.NEW_COLUMN TO VALOR_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
UPDATE PRODUCTO SET NEW_COLUMN=PRECIO_DISTRIBUIDOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO DROP COLUMN PRECIO_DISTRIBUIDOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
RENAME COLUMN PRODUCTO.NEW_COLUMN TO PRECIO_DISTRIBUIDOR;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
UPDATE PRODUCTO SET NEW_COLUMN=PRECIO_TARJETA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO DROP COLUMN PRECIO_TARJETA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
RENAME COLUMN PRODUCTO.NEW_COLUMN TO PRECIO_TARJETA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE GUIA_REMISION ADD DIRECCION_ESTABLECIMIENTO varchar(1024);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE GUIA_REMISION ADD DIRECCION_MATRIZ varchar(1024);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE DESTINATARIO_GUIA_REMISION ADD CODIGO_ESTABLECIMIENTO varchar(4);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.3,MOSTRAR_ERROR=SI)*/
INSERT INTO PARAMETRO (NOMBRE,VALOR) VALUES('tipo_envio_comprobante','f');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.4)*/
ALTER TABLE GUIA_REMISION ADD TIPO_AMBIENTE varchar(1);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.4)*/
ALTER TABLE GUIA_REMISION ADD FECHA_AUTORIZACION_SRI date;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.5,MOSTRAR_ERROR=SI)*/
INSERT INTO ACTUALIZAR_SISTEMA (NOMBRE_METODO,VERSION,CAMBIO_ACTUALIZADO,DESCRIPCION) VALUES('actualizaComprobantesElectronicos','1.2.7.0.5','n','Actuliza todos los comprobantes anteriores para saber cuales fueron eliminados por el Sri');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.5,MOSTRAR_ERROR=NO)*/
INSERT INTO PERMISO_VENTANA(PERFIL_ID,NOMBRE_CLASE,PERMISO_GRABAR,PERMISO_ELIMINAR,PERMISO_IMPRIMIR,PERMISO_EDITAR,PERMISO_BUSCAR) VALUES(1,'UECT','s','s','s','s','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.5,MOSTRAR_ERROR=SI)*/
ALTER TABLE CLIENTE ALTER CORREO_ELECTRONICO SET DATA TYPE VARCHAR(300);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.9,MOSTRAR_ERROR=NO)*/
ALTER TABLE GUIA_REMISION ADD FECHA_AUTORIZACION_SRI date;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.0.9,MOSTRAR_ERROR=NO)*/
ALTER TABLE GUIA_REMISION ADD TIPO_AMBIENTE varchar(1);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE DESTINATARIO_GUIA_REMISION ADD SUCURSAL_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.0,MOSTRAR_ERROR=SI)*/
INSERT INTO ACTUALIZAR_SISTEMA (NOMBRE_METODO,VERSION,CAMBIO_ACTUALIZADO,DESCRIPCION) VALUES('actualizarSucursalesEmpresas','1.2.7.8.0','n','Crea sucursales de todos los clientes que existen');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.2,MOSTRAR_ERROR=NO)*/
UPDATE PRODUCTO SET TRANSPORTAR_EN_GUIA_REMISION='s';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.2,MOSTRAR_ERROR=NO)*/
INSERT INTO PERMISO_VENTANA(PERFIL_ID,NOMBRE_CLASE,PERMISO_GRABAR,PERMISO_ELIMINAR,PERMISO_IMPRIMIR,PERMISO_EDITAR,PERMISO_BUSCAR) VALUES(1,'ICDB','s','s','s','s','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.6,MOSTRAR_ERROR=NO)*/
INSERT INTO PERMISO_VENTANA(PERFIL_ID,NOMBRE_CLASE,PERMISO_GRABAR,PERMISO_ELIMINAR,PERMISO_IMPRIMIR,PERMISO_EDITAR,PERMISO_BUSCAR) VALUES(1,'CFDF','s','s','s','s','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRESUPUESTO_DETALLE ADD CANTIDAD decimal(13,2);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.8.9,MOSTRAR_ERROR=SI)*/
ALTER TABLE PARAMETRO ALTER VALOR SET DATA TYPE VARCHAR(2048);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.0,MOSTRAR_ERROR=SI)*/
ALTER TABLE DEPARTAMENTO ALTER NOMBRE SET DATA TYPE VARCHAR(100);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.0,MOSTRAR_ERROR=SI)*/
ALTER TABLE DEPARTAMENTO ALTER DESCRIPCION SET DATA TYPE VARCHAR(1024);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE COMPRA ADD AUTORIZACION VARCHAR(60);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.0,MOSTRAR_ERROR=NO)*/
ALTER TABLE COMPRA ADD TIPO_IDENTIFICACION_CODIGO_SRI varchar(3);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.4,MOSTRAR_ERROR=SI)*/
ALTER TABLE COMPRA_DETALLE ADD CODIGO_SUSTENTO_SRI varchar(16);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
UPDATE CLIENTE SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
ALTER TABLE NOTA_CREDITO DROP CONSTRAINT id_cliente_nota_credito_fk;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
ALTER TABLE COMPRA DROP CONSTRAINT id_cliente_compra_fk;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
ALTER TABLE ORDEN_COMPRA DROP CONSTRAINT id_cliente_orden_compra_fk;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
ALTER TABLE FACTURA DROP CONSTRAINT id_cliente_factura_fk;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE CLIENTE DROP CONSTRAINT SQL180523095636851;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE FACTURA DROP COLUMN EMPRESA_ID;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE FACTURA ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE FACTURA SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE PARAMETRO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE CATALOGO_PRODUCTO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE PRODUCTO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN EMPRESA_ID;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE NOTA_CREDITO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE CATEGORIA_PRODUCTO ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE CATEGORIA_PRODUCTO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE RETENCION DROP COLUMN EMPRESA_ID;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE RETENCION ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE RETENCION SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE COMPRA DROP COLUMN EMPRESA_ID;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE COMPRA ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE COMPRA SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE TRANSPORTISTA ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE TRANSPORTISTA SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
ALTER TABLE PERFIL_USUARIO DROP CONSTRAINT ID_PERFIL_USUARIO_FK;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=SI)*/
ALTER TABLE PERFIL_USUARIO DROP CONSTRAINT ID_USUARIO_PERFIL_FK;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE USUARIO DROP CONSTRAINT SQL180523095637160;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE USUARIO ADD ID BIGINT NOT NULL primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE USUARIO ADD ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE USUARIO ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE USUARIO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE PERFIL ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE PERFIL SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
ALTER TABLE PERFIL_USUARIO ADD COLUMN USUARIO_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE PERFIL_USUARIO PU SET PU.USUARIO_ID=(SELECT ID FROM USUARIO WHERE NICK=PU.NICK);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO DROP CONSTRAINT SQL180523095639001;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE PARAMETRO ADD COLUMN EMPRESA_ID BIGINT;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.7)*/
UPDATE PARAMETRO SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.8,MOSTRAR_ERROR=SI)*/
INSERT INTO ACTUALIZAR_SISTEMA (NOMBRE_METODO,VERSION,CAMBIO_ACTUALIZADO,DESCRIPCION) VALUES('actualizarPuntoEmisionUsuario','1.2.7.9.8','n','Crea las relaciones de los usuarios con los perfiles');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.8,MOSTRAR_ERROR=SI)*/
UPDATE BODEGA SET ESTADO='A' WHERE ESTADO='a';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.8,MOSTRAR_ERROR=SI)*/
UPDATE BODEGA SET SUCURSAL_ID =(SELECT ID FROM SUCURSAL fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.8,MOSTRAR_ERROR=SI)*/
UPDATE BODEGA SET  TIPO_BODEGA='v' WHERE BODEGA_ID =(SELECT BODEGA_ID FROM KARDEX fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.8,MOSTRAR_ERROR=SI)*/
UPDATE BODEGA SET EMPRESA_ID =(SELECT ID FROM EMPRESA fetch first 1 rows only) ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.7.9.9,MOSTRAR_ERROR=NO)*/
ALTER TABLE GUIA_REMISION ADD COLUMN SUCURSAL_EMPRESA_ID BIGINT;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE PUNTO_EMISION ADD SECUENCIAL_NOTA_VENTA_INTERNA BIGINT;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE COMPRA_DETALLE  ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.1,MOSTRAR_ERROR=NO)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=CANTIDAD ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN CANTIDAD ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.1,MOSTRAR_ERROR=NO)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO CANTIDAD ;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.3,MOSTRAR_ERROR=SI)*/
ALTER TABLE FACTURA_DETALLE ALTER DESCRIPCION SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.3,MOSTRAR_ERROR=SI)*/
ALTER TABLE CARTERA_DETALLE ALTER DESCRIPCION SET DATA TYPE VARCHAR(300);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.3,MOSTRAR_ERROR=SI)*/
ALTER TABLE NOTA_CREDITO_DETALLE ALTER DESCRIPCION SET DATA TYPE VARCHAR(300);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Lata 5.5% detal',1.65,'Lata 5.5% detal');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Botella 5.5% detal',1.65,'Botella 5.5% detal');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Botella 6% detal',1.80,'Botella 6% detal');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Lata 5.5% supermaxi',2.1353,'Lata 5.5% supermaxi');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Botella 5.5% supermaxi',2.1353,'Botella 5.5% supermaxi');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Botella 5.5% publico',1.4398,'Botella 5.5% publico');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.8,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Botella 6% publico',1.5726,'Botella 6% publico');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.0.9,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE ADD FECHA_DOCUMENTO date;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.1,MOSTRAR_ERROR=NO)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'332G','PAGOS CON TARJETA DE CREDITO',0.0000,'2015-03-01 00:00:00',NULL);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.2,MOSTRAR_ERROR=NO)*/
UPDATE BODEGA SET ESTADO='E' WHERE DESCRIPCION='Bodega por defecto' AND (SELECT COUNT(*) AS CANTIDAD FROM BODEGA WHERE ESTADO='A')>1;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.3,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX SET ESTADO='A';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.4,MOSTRAR_ERROR=SI)*/
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2,3041,'Botella 6% publico',1.5726,'Botella 6% publico');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.5,MOSTRAR_ERROR=SI)*/
UPDATE KARDEX SET ESTADO='A';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.6,MOSTRAR_ERROR=SI)*/
UPDATE EMPRESA SET CODIGO =SUBSTR(RAZON_SOCIAL,1,3)  WHERE CODIGO IS NULL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.6,MOSTRAR_ERROR=SI)*/
UPDATE SUCURSAL SET CODIGO =SUBSTR(NOMBRE,1,3)  WHERE CODIGO IS NULL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.1.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ADD COLUMN OCULTAR_DETALLE_VENTA varchar(1);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.2,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ALTER CARACTERISTICAS SET DATA TYPE VARCHAR(5000);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.2,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ALTER OBSERVACIONES SET DATA TYPE VARCHAR(5000);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.6,MOSTRAR_ERROR=NO)*/
INSERT INTO COMPONENTE_COMPROBANTE_FISICO (BANDA_COMPROBANTE_ID,NOMBRE,UUID,X,Y,ANCHO,ALTO,TAMANIO_LETRA,NEGRITA,OCULTO)
    VALUES (3,'formaPagoEfectivo','7884b397-66d7-481f-bb9c-5b797e66cf6c',172,21,69,15,10,'n','s'),
          (3,'formaPagoCheque','1e3ff100-b5f3-4f41-8546-a4bab11c618e',172,36,69,15,10,'n','s'),
          (3,'formaPagoDineroElec','a320d71f-4e5d-42a1-943b-c67bb2520ea6',172,51,69,15,10,'n','s'),
          (3,'formaPagoTarjetaCred','0061e225-2555-43ea-96b1-5a3a5990c0a4',172,66,69,15,10,'n','s'),
          (3,'formaPagoOtros','773022d8-63ad-475c-adb6-1bc251ce1fd4',172,81,69,15,10,'n','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
ALTER TABLE SRI_RETENCION_RENTA ADD COLUMN NEW_COLUMN decimal(13,4);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
UPDATE SRI_RETENCION_RENTA SET NEW_COLUMN=PORCENTAJE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
ALTER TABLE SRI_RETENCION_RENTA DROP COLUMN PORCENTAJE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
RENAME COLUMN SRI_RETENCION_RENTA.NEW_COLUMN TO PORCENTAJE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
UPDATE SRI_RETENCION_RENTA SET PORCENTAJE=1.75 WHERE CODIGO_SRI='312';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
UPDATE SRI_RETENCION_RENTA SET PORCENTAJE=1.75 WHERE CODIGO_SRI='309';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
UPDATE SRI_RETENCION_RENTA SET PORCENTAJE=1.75 WHERE CODIGO_SRI='319';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
UPDATE SRI_RETENCION_RENTA SET PORCENTAJE=1.75 WHERE CODIGO_SRI='322';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
UPDATE SRI_RETENCION_RENTA SET PORCENTAJE=1.75 WHERE CODIGO_SRI='343B';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.7)*/
INSERT INTO SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) VALUES(1,'3440','Otras retenciones aplicables el 2,75%',2.7500,'2020-04-07 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.8)*/
INSERT INTO SRI_FORMA_PAGO (NOMBRE,ALIAS, CODIGO,FECHA_INICIO) VALUES  ('SIN UTILIZACION DEL SISTEMA FINANCIERO','Cartera', '01', '2021-04-04');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.9)*/
UPDATE EMPRESA SET ESTADO='A';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.2.9)*/
INSERT INTO PARAMETRO (NOMBRE,VALOR) VALUES('habilitar_retencion_compras','s');
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.3.0)*/
UPDATE IMPUESTO_DETALLE SET FECHA_FIN =NULL WHERE CODIGO=2;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.3.0)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'312A','COMPRA DE BIENES DE ORIGEN AGRICOLA, AVICOLA, PECUARIO',1,'2009-03-20 00:00:00',NULL);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.3.5)*/
ALTER TABLE ARQUEO_CAJA DROP COLUMN VALOR_TEORICO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.3.5)*/
ALTER TABLE ARQUEO_CAJA ADD VALOR_TEORICO decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.3.8)*/
UPDATE USUARIO SET FILTRAR_FACTURA='n';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.4.9,MOSTRAR_ERROR=NO)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'346','OTRAS RETENCIONES APLICABLES A OTROS PERSONAJES',1.7500,'2020-10-01 00:00:00',NULL);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.0,MOSTRAR_ERROR=NO)*/
insert into SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'000','NO APLICA',0,'2020-10-01 00:00:00',NULL);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE FACTURA_DETALLE  ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=CANTIDAD ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN CANTIDAD ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO CANTIDAD ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE NOTA_CREDITO_DETALLE  ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
UPDATE NOTA_CREDITO_DETALLE SET NEW_COLUMN=CANTIDAD ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE NOTA_CREDITO_DETALLE DROP COLUMN CANTIDAD ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
RENAME COLUMN NOTA_CREDITO_DETALLE.NEW_COLUMN TO CANTIDAD ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE FACTURA  ADD COLUMN NEW_COLUMN TIMESTAMP;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
UPDATE FACTURA SET NEW_COLUMN=CAST(FECHA_CREACION AS TIMESTAMP );
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE FACTURA DROP COLUMN FECHA_CREACION ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.1,MOSTRAR_ERROR=NO)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO FECHA_CREACION ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX SET NEW_COLUMN=STOCK;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX DROP COLUMN STOCK;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
RENAME COLUMN KARDEX.NEW_COLUMN TO STOCK;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=CANTIDAD;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN CANTIDAD;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.2,MOSTRAR_ERROR=NO)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO CANTIDAD;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE  ADD COLUMN NEW_COLUMN TIMESTAMP;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=CAST(FECHA_CREACION AS TIMESTAMP);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN FECHA_CREACION ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO FECHA_CREACION ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE  ADD COLUMN NEW_COLUMN TIMESTAMP;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=CAST(FECHA_INGRESO AS TIMESTAMP) ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN FECHA_INGRESO ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.5.4,MOSTRAR_ERROR=NO)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO FECHA_INGRESO ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.7.3,MOSTRAR_ERROR=NO)*/
INSERT INTO SRI_RETENCION_RENTA (RETENCION_ID, CODIGO_SRI, NOMBRE, PORCENTAJE, FECHA_INICIO, FECHA_FIN) values(1,'351','RÉGIMEN MICROEMPRESARIAL',1.75,'2021-01-06 00:00:00',NULL);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.8.1,MOSTRAR_ERROR=NO)*/
UPDATE FACTURA SET ESTADO_NOTA_CREDITO='N' WHERE ESTADO_NOTA_CREDITO IS NULL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.8.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ALTER CARACTERISTICAS SET DATA TYPE VARCHAR(1024);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.8.1,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO ALTER OBSERVACIONES SET DATA TYPE VARCHAR(1024);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.2,MOSTRAR_ERROR=NO)*/
UPDATE PERSONA_ESTABLECIMIENTO SET ESTADO='A';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
UPDATE SRI_RETENCION_RENTA SET PORCENTAJE =3 WHERE CODIGO_SRI ='340';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
UPDATE PERSONA_ESTABLECIMIENTO SET DIRECCION='s/n' WHERE NOMBRE_COMERCIAL ='CONSUMIDOR FINAL';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE EMPRESA ALTER NOMBRE_LEGAL SET DATA TYPE VARCHAR(300);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE EMPRESA ALTER RAZON_SOCIAL SET DATA TYPE VARCHAR(300);

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE  ADD COLUMN NEW_COLUMN TIMESTAMP;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=CAST(FECHA_CREACION AS TIMESTAMP);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN FECHA_CREACION ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO FECHA_CREACION ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE  ADD COLUMN NEW_COLUMN TIMESTAMP;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=CAST(FECHA_INGRESO AS TIMESTAMP) ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN FECHA_INGRESO ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.6,MOSTRAR_ERROR=NO)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO FECHA_INGRESO ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.7,MOSTRAR_ERROR=NO)*/
UPDATE PERSONA_ESTABLECIMIENTO SET DIRECCION ='s/n' WHERE DIRECCION = '';


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO_ENSAMBLE ADD COLUMN NEW_COLUMN decimal(13,5);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.7,MOSTRAR_ERROR=NO)*/
UPDATE PRODUCTO_ENSAMBLE SET NEW_COLUMN=CANTIDAD;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.7,MOSTRAR_ERROR=NO)*/
ALTER TABLE PRODUCTO_ENSAMBLE DROP COLUMN CANTIDAD;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.7,MOSTRAR_ERROR=NO)*/
RENAME COLUMN PRODUCTO_ENSAMBLE.NEW_COLUMN TO CANTIDAD;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.8,MOSTRAR_ERROR=NO)*/
ALTER TABLE CARTERA  ADD COLUMN NEW_COLUMN TIMESTAMP;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.8,MOSTRAR_ERROR=NO)*/
UPDATE CARTERA SET NEW_COLUMN=CAST(FECHA_CREACION AS TIMESTAMP);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.8,MOSTRAR_ERROR=NO)*/
ALTER TABLE CARTERA DROP COLUMN FECHA_CREACION ;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.8,MOSTRAR_ERROR=NO)*/
RENAME COLUMN CARTERA.NEW_COLUMN TO FECHA_CREACION ;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.8.9.9,MOSTRAR_ERROR=SI)*/
INSERT INTO ACTUALIZAR_SISTEMA (NOMBRE_METODO,VERSION,CAMBIO_ACTUALIZADO,DESCRIPCION) VALUES('actualizarMicroempresaARimpe','1.2.8.9.9','n','Permite actualizar el nuevo regimen Rimpe a las empresa que estab como microempresa');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.0,MOSTRAR_ERROR=SI)*/
UPDATE SRI_RETENCION_RENTA SET NOMBRE ='NEGOCIOS POPULARES', PORCENTAJE =0 WHERE CODIGO_SRI ='332';
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.0,MOSTRAR_ERROR=SI)*/
UPDATE SRI_RETENCION_RENTA SET NOMBRE ='EMPRENDEDORES', PORCENTAJE =1 WHERE CODIGO_SRI ='343';

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE FACTURA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE NOTA_CREDITO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE NOTA_CREDITO_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE NOTA_CREDITO_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN NOTA_CREDITO_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE KARDEX_DETALLE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE CARTERA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE CARTERA_DETALLE SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE CARTERA_DETALLE DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN CARTERA_DETALLE.NEW_COLUMN TO TOTAL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE KARDEX_DETALLE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO SALDO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE CARTERA_CRUCE ADD COLUMN NEW_COLUMN decimal(13,6);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
UPDATE CARTERA_CRUCE SET NEW_COLUMN=VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
ALTER TABLE CARTERA_CRUCE DROP COLUMN VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.1,MOSTRAR_ERROR=SI)*/
RENAME COLUMN CARTERA_CRUCE.NEW_COLUMN TO VALOR;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.3,MOSTRAR_ERROR=SI)*/
INSERT INTO COMPONENTE_COMPROBANTE_FISICO (BANDA_COMPROBANTE_ID,NOMBRE,UUID,X,Y,ANCHO,ALTO,TAMANIO_LETRA,NEGRITA,OCULTO) VALUES (1,'guiaRemision','60338b1e-f1dc-4065-ab8f-ce5dbc1cee44',389,35,133,12,10,'n','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.7,MOSTRAR_ERROR=SI)*/
INSERT INTO COMPONENTE_COMPROBANTE_FISICO (BANDA_COMPROBANTE_ID,NOMBRE,UUID,X,Y,ANCHO,ALTO,TAMANIO_LETRA,NEGRITA,OCULTO) VALUES (2,'ivaDetalle','da4670c8-a585-4e0b-bb67-417c5efd01e3',350,0,37,12,10,'n','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.9,MOSTRAR_ERROR=SI)*/
UPDATE COMPROBANTE_FISICO_DISENIO SET PPP=72;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.9,MOSTRAR_ERROR=SI)*/
INSERT INTO COMPONENTE_COMPROBANTE_FISICO (BANDA_COMPROBANTE_ID,NOMBRE,UUID,X,Y,ANCHO,ALTO,TAMANIO_LETRA,NEGRITA,OCULTO) VALUES (3,'lineaFinal','4ead026f-bfbb-4dbb-9189-f0cb97eb039a',0,1,50,1,10,'n','s');

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.9,MOSTRAR_ERROR=SI)*/
UPDATE BANDA_COMPROBANTE SET ALTO =ALTO+20 WHERE NOMBRE IN ('pageHeader','columnFooter') AND COMPROBANTE_FISICO_ID=1;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.9.0.9,MOSTRAR_ERROR=SI)*/
UPDATE COMPONENTE_COMPROBANTE_FISICO SET Y=Y+20 WHERE BANDA_COMPROBANTE_ID =1;

