/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA SET NEW_COLUMN=DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA DROP COLUMN DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA.NEW_COLUMN TO DESCUENTO_IVA;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA SET NEW_COLUMN=DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA DROP COLUMN DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA.NEW_COLUMN TO DESCUENTO_IVA_CERO;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA SET NEW_COLUMN=SUBTOTAL_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA DROP COLUMN SUBTOTAL_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA.NEW_COLUMN TO SUBTOTAL_IVA;


/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA SET NEW_COLUMN=SUBTOTAL_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA DROP COLUMN SUBTOTAL_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA.NEW_COLUMN TO SUBTOTAL_IVA_CERO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA.NEW_COLUMN TO IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA.NEW_COLUMN TO TOTAL;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO DESCUENTO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=VALOR_RETENCION_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN VALOR_RETENCION_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO VALOR_RETENCION_IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=VALOR_RETENCION_RENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN VALOR_RETENCION_RENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO VALOR_RETENCION_RENTA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE COMPRA_DETALLE SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE COMPRA_DETALLE DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN COMPRA_DETALLE.NEW_COLUMN TO TOTAL;






/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA.NEW_COLUMN TO IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA.NEW_COLUMN TO TOTAL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA SET NEW_COLUMN=DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA DROP COLUMN DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA.NEW_COLUMN TO DESCUENTO_IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA SET NEW_COLUMN=DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA DROP COLUMN DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA.NEW_COLUMN TO DESCUENTO_IVA_CERO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA SET NEW_COLUMN=SUBTOTAL_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA DROP COLUMN SUBTOTAL_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA.NEW_COLUMN TO SUBTOTAL_IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA SET NEW_COLUMN=SUBTOTAL_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA DROP COLUMN SUBTOTAL_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA.NEW_COLUMN TO SUBTOTAL_IVA_CERO;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA_DETALLE SET NEW_COLUMN=DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE DROP COLUMN DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA_DETALLE.NEW_COLUMN TO DESCUENTO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA_DETALLE SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA_DETALLE.NEW_COLUMN TO TOTAL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE ORDEN_COMPRA_DETALLE SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE ORDEN_COMPRA_DETALLE DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN ORDEN_COMPRA_DETALLE.NEW_COLUMN TO IVA;








/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA SET NEW_COLUMN=DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA DROP COLUMN DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO DESCUENTO_IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA SET NEW_COLUMN=DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA DROP COLUMN DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO DESCUENTO_IVA_CERO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA SET NEW_COLUMN=SUBTOTAL_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA DROP COLUMN SUBTOTAL_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO SUBTOTAL_IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA SET NEW_COLUMN=SUBTOTAL_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA DROP COLUMN SUBTOTAL_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO SUBTOTAL_IVA_CERO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA.NEW_COLUMN TO TOTAL;







/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO DESCUENTO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=VALOR_ICE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN VALOR_ICE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO VALOR_ICE;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA_DETALLE SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_DETALLE DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA_DETALLE.NEW_COLUMN TO TOTAL;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_FORMA_PAGO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE FACTURA_FORMA_PAGO SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE FACTURA_FORMA_PAGO DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN FACTURA_FORMA_PAGO.NEW_COLUMN TO TOTAL;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE IMPUESTO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE IMPUESTO_DETALLE SET NEW_COLUMN=PORCENTAJE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE IMPUESTO_DETALLE DROP COLUMN PORCENTAJE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN IMPUESTO_DETALLE.NEW_COLUMN TO PORCENTAJE;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE KARDEX SET NEW_COLUMN=PRECIO_PROMEDIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX DROP COLUMN PRECIO_PROMEDIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN KARDEX.NEW_COLUMN TO PRECIO_PROMEDIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE KARDEX SET NEW_COLUMN=PRECIO_ULTIMO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX DROP COLUMN PRECIO_ULTIMO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN KARDEX.NEW_COLUMN TO PRECIO_ULTIMO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE KARDEX SET NEW_COLUMN=PRECIO_TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX DROP COLUMN PRECIO_TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN KARDEX.NEW_COLUMN TO PRECIO_TOTAL;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE KARDEX_DETALLE SET NEW_COLUMN=PRECIO_TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE KARDEX_DETALLE DROP COLUMN PRECIO_TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN KARDEX_DETALLE.NEW_COLUMN TO PRECIO_TOTAL;






/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBROS_NIVEL ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RUBROS_NIVEL SET NEW_COLUMN=VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBROS_NIVEL DROP COLUMN VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RUBROS_NIVEL.NEW_COLUMN TO VALOR;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_ESTUDIANTE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RUBRO_ESTUDIANTE SET NEW_COLUMN=VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_ESTUDIANTE DROP COLUMN VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RUBRO_ESTUDIANTE.NEW_COLUMN TO VALOR;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_ESTUDIANTE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RUBRO_ESTUDIANTE SET NEW_COLUMN=SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_ESTUDIANTE DROP COLUMN SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RUBRO_ESTUDIANTE.NEW_COLUMN TO SALDO;




/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_PLANTILLA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RUBRO_PLANTILLA SET NEW_COLUMN=VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RUBRO_PLANTILLA DROP COLUMN VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RUBRO_PLANTILLA.NEW_COLUMN TO VALOR;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE CARTERA SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN CARTERA.NEW_COLUMN TO TOTAL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE CARTERA SET NEW_COLUMN=SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA DROP COLUMN SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN CARTERA.NEW_COLUMN TO SALDO;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE CARTERA_DETALLE SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_DETALLE DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN CARTERA_DETALLE.NEW_COLUMN TO TOTAL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE CARTERA_DETALLE SET NEW_COLUMN=SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_DETALLE DROP COLUMN SALDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN CARTERA_DETALLE.NEW_COLUMN TO SALDO;



/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_CRUCE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE CARTERA_CRUCE SET NEW_COLUMN=VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE CARTERA_CRUCE DROP COLUMN VALOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN CARTERA_CRUCE.NEW_COLUMN TO VALOR;




/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=SUBTOTAL_SIN_IMPUESTOS;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN SUBTOTAL_SIN_IMPUESTOS;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO SUBTOTAL_SIN_IMPUESTOS;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=SUBTOTAL_DOCE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN SUBTOTAL_DOCE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO SUBTOTAL_DOCE;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=SUBTOTAL_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN SUBTOTAL_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO SUBTOTAL_CERO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=VALOR_IVA_DOCE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN VALOR_IVA_DOCE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO VALOR_IVA_DOCE;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=VALOR_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN VALOR_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO VALOR_IVA_CERO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO TOTAL;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN DESCUENTO_IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO DESCUENTO_IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO SET NEW_COLUMN=DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO DROP COLUMN DESCUENTO_IVA_CERO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO.NEW_COLUMN TO DESCUENTO_IVA_CERO;






/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO_DETALLE SET NEW_COLUMN=PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE DROP COLUMN PRECIO_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO_DETALLE.NEW_COLUMN TO PRECIO_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO_DETALLE SET NEW_COLUMN=DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE DROP COLUMN DESCUENTO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO_DETALLE.NEW_COLUMN TO DESCUENTO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO_DETALLE SET NEW_COLUMN=IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE DROP COLUMN IVA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO_DETALLE.NEW_COLUMN TO IVA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE NOTA_CREDITO_DETALLE SET NEW_COLUMN=TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE NOTA_CREDITO_DETALLE DROP COLUMN TOTAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN NOTA_CREDITO_DETALLE.NEW_COLUMN TO TOTAL;






/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRODUCTO SET NEW_COLUMN=VALOR_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO DROP COLUMN VALOR_UNITARIO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRODUCTO.NEW_COLUMN TO VALOR_UNITARIO;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRODUCTO SET NEW_COLUMN=PRECIO_DISTRIBUIDOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO DROP COLUMN PRECIO_DISTRIBUIDOR;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRODUCTO.NEW_COLUMN TO PRECIO_DISTRIBUIDOR;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRODUCTO SET NEW_COLUMN=PRECIO_TARJETA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO DROP COLUMN PRECIO_TARJETA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRODUCTO.NEW_COLUMN TO PRECIO_TARJETA;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO_PROVEEDOR ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRODUCTO_PROVEEDOR SET NEW_COLUMN=COSTO_ACTUAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRODUCTO_PROVEEDOR DROP COLUMN COSTO_ACTUAL;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRODUCTO_PROVEEDOR.NEW_COLUMN TO COSTO_ACTUAL;




/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RETENCION_DETALLE SET NEW_COLUMN=BASE_IMPONIBLE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE DROP COLUMN BASE_IMPONIBLE;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RETENCION_DETALLE.NEW_COLUMN TO BASE_IMPONIBLE;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RETENCION_DETALLE SET NEW_COLUMN=PORCENTAJE_RETENER;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE DROP COLUMN PORCENTAJE_RETENER;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RETENCION_DETALLE.NEW_COLUMN TO PORCENTAJE_RETENER;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE ADD COLUMN NEW_COLUMN decimal(13,3);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE RETENCION_DETALLE SET NEW_COLUMN=VALOR_RETENIDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE RETENCION_DETALLE DROP COLUMN VALOR_RETENIDO;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN RETENCION_DETALLE.NEW_COLUMN TO VALOR_RETENIDO;





/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO SET NEW_COLUMN=DESCUENTO_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO DROP COLUMN DESCUENTO_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO.NEW_COLUMN TO DESCUENTO_COMPRA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO SET NEW_COLUMN=DESCUENTO_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO DROP COLUMN DESCUENTO_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO.NEW_COLUMN TO DESCUENTO_VENTA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO SET NEW_COLUMN=TOTAL_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO DROP COLUMN TOTAL_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO.NEW_COLUMN TO TOTAL_COMPRA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO SET NEW_COLUMN=TOTAL_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO DROP COLUMN TOTAL_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO.NEW_COLUMN TO TOTAL_VENTA;




/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO_DETALLE SET NEW_COLUMN=PRECIO_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE DROP COLUMN PRECIO_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO_DETALLE.NEW_COLUMN TO PRECIO_COMPRA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO_DETALLE SET NEW_COLUMN=DESCUENTO_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE DROP COLUMN DESCUENTO_COMPRA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO_DETALLE.NEW_COLUMN TO DESCUENTO_COMPRA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO_DETALLE SET NEW_COLUMN=PRECIO_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE DROP COLUMN PRECIO_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO_DETALLE.NEW_COLUMN TO PRECIO_VENTA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO_DETALLE SET NEW_COLUMN=DESCUENTO_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE DROP COLUMN DESCUENTO_VENTA;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO_DETALLE.NEW_COLUMN TO DESCUENTO_VENTA;

/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE ADD COLUMN NEW_COLUMN decimal(13,2);
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
UPDATE PRESUPUESTO_DETALLE SET NEW_COLUMN=CANTIDAD;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
ALTER TABLE PRESUPUESTO_DETALLE DROP COLUMN CANTIDAD;
/*@AGREGAR_SCRIPT (VERSION_SISTEMA=1.2.6.9.5)*/
RENAME COLUMN PRESUPUESTO_DETALLE.NEW_COLUMN TO TOTAL_VENTA;


