/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.crm.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.componentes.ComponenteEnvioCorreoPanel;
import ec.com.codesoft.codefaclite.controlador.componentes.ComponenteEnvioSmsPanel;
import ec.com.codesoft.codefaclite.corecodefaclite.util.CampoBuscarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.CursorPorDefectoAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ComponenteSecundarioAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.FormaPago;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.Nacionalidad;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.Persona;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.SriFormaPago;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.SriIdentificacion;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.Sucursal.TipoSucursalEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.TipoEstablecimiento;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.Zona;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.GeneralEnumEstado;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.OperadorNegocioEnum;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.PlantillaSmsEnum;
import ec.com.codesoft.codefaclite.utilidades.validadores.ExpresionRegular;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public abstract class ClienteForm extends ControladorCodefacInterface {
    public static final String NOMBRE_VALIDADOR_IDENTIFICACION="Identificacion";
    private ComponenteEnvioSmsPanel pnlSms=new ComponenteEnvioSmsPanel();
    private ComponenteEnvioCorreoPanel pnlCorreo=new ComponenteEnvioCorreoPanel();
    
    /**
     * Creates new form clienteForm
     */
    public ClienteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCaracteristicasGenerales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboIdentificacion = new javax.swing.JComboBox<>();
        jTextIdentificacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextExtension = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jTextNombreSocial = new javax.swing.JTextField();
        lblEspacio = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbNacionalidad = new javax.swing.JComboBox<>();
        lblEspacio5 = new javax.swing.JLabel();
        lblEspacio8 = new javax.swing.JLabel();
        lblEspacio6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNombreLegal = new javax.swing.JTextField();
        jTextAreaDireccion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNombreContacto = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextReferenciaDireccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboTipoCliente = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoOperador = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cmbFormaPagoDefecto = new javax.swing.JComboBox<>();
        lblOligadoLlevarContabilidad = new javax.swing.JLabel();
        chkObligadoLlevarContabilidad = new javax.swing.JCheckBox();
        lblEspacio7 = new javax.swing.JLabel();
        lblEspacio4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDiasCredito = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        txtDiasCreditoProveedor = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        txtCodigoPersonalizado = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cmbZona = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkContacto = new javax.swing.JCheckBox();
        lblEspacioHorizontal = new javax.swing.JLabel();
        lblEspacioVertical = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPorcentajeComision = new javax.swing.JTextField();
        jPanelCaracteristicasGenerales1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextTelefonoEstablecimiento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextExtensionEstablecimiento = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextCelularEstablecimiento = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lblEspacio9 = new javax.swing.JLabel();
        lblEspacio11 = new javax.swing.JLabel();
        txtNombreLegalEstablecimiento = new javax.swing.JTextField();
        jTextAreaDireccionEstablecimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstablecimientos = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCodigoEstablecimiento = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        cmbTipoEstablecimiento = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        txtCodigoPersonalizadoOficina = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        txtLatitud = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        cmbZonaOficina = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        cmbTipoClienteOficina = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jTextReferenciaDireccionEstablecimiento = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnAgregarEstablecimiento = new javax.swing.JButton();
        btnEditarEstablecimiento = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cliente");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/persona-ico.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 420));

        jPanelCaracteristicasGenerales.setPreferredSize(new java.awt.Dimension(707, 353));
        jPanelCaracteristicasGenerales.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextNombres, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel3, gridBagConstraints);

        jComboIdentificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jComboIdentificacion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        jPanelCaracteristicasGenerales.add(jTextIdentificacion, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Teléfono Convencional:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanelCaracteristicasGenerales.add(jTextTelefono, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Referencia Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextExtension, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Teléfono Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextCelular, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Correo Electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales.add(jTextCorreo, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Identificación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel4, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel11, gridBagConstraints);

        cmbEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(cmbEstado, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Nombre Contacto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextApellidos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextNombreSocial, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        jPanelCaracteristicasGenerales.add(lblEspacio, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Nacionalidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel15, gridBagConstraints);

        cmbNacionalidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(cmbNacionalidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanelCaracteristicasGenerales.add(lblEspacio5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanelCaracteristicasGenerales.add(lblEspacio8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        jPanelCaracteristicasGenerales.add(lblEspacio6, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Razón Social:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(txtNombreLegal, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextAreaDireccion, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Nombre Legal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(txtNombreContacto, gridBagConstraints);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("Extensión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales.add(jLabel38, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales.add(jTextReferenciaDireccion, gridBagConstraints);

        jTabbedPane1.addTab("Datos Principales", jPanelCaracteristicasGenerales);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Observaciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel5, gridBagConstraints);

        jComboTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "SUJETO RETENIDO", "DESTINATARIO" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jComboTipoCliente, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(cmbTipoOperador, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Días de Credito Proveedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cmbFormaPagoDefecto, gridBagConstraints);

        lblOligadoLlevarContabilidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOligadoLlevarContabilidad.setText("Obligado a Llevar Contabilidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(lblOligadoLlevarContabilidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(chkObligadoLlevarContabilidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(lblEspacio7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        jPanel1.add(lblEspacio4, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Forma Pago Defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDiasCredito, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Días de Credito Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel28, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtDiasCreditoProveedor, gridBagConstraints);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Tipo Establecimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel29, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtCodigoPersonalizado, gridBagConstraints);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("Tipo Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel35, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cmbZona, gridBagConstraints);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel37.setText("Zona:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel37, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cmbTipoCliente, gridBagConstraints);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText("Código Personalizado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel40, gridBagConstraints);

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jTabbedPane1.addTab("Datos Adicionales", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Contacto clientes recomendados:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(chkContacto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(lblEspacioHorizontal, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(lblEspacioVertical, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Porcentaje Comisión :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel18, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        jPanel2.add(txtPorcentajeComision, gridBagConstraints);

        jTabbedPane1.addTab("Referencias", jPanel2);

        jPanelCaracteristicasGenerales1.setPreferredSize(new java.awt.Dimension(707, 353));
        jPanelCaracteristicasGenerales1.setLayout(new java.awt.GridBagLayout());

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Referencia Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel22, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Latitud:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel23, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanelCaracteristicasGenerales1.add(jTextTelefonoEstablecimiento, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Extensión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel24, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jTextExtensionEstablecimiento, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Categoria Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel25, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales1.add(jTextCelularEstablecimiento, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Código Personalizado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel30, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanelCaracteristicasGenerales1.add(lblEspacio9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        jPanelCaracteristicasGenerales1.add(lblEspacio11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(txtNombreLegalEstablecimiento, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(jTextAreaDireccionEstablecimiento, gridBagConstraints);

        jScrollPane1.setViewportView(tblEstablecimientos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanelCaracteristicasGenerales1.add(jLabel20, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Teléfono Celular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel26, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(txtCodigoEstablecimiento, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Teléfono Convencional:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel27, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(cmbTipoEstablecimiento, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("Nombre Establecimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel31, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(txtCodigoPersonalizadoOficina, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Longitud:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel32, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Tipo Establecimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel33, gridBagConstraints);

        txtLongitud.setEditable(false);
        txtLongitud.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(txtLongitud, gridBagConstraints);

        txtLatitud.setEditable(false);
        txtLatitud.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(txtLatitud, gridBagConstraints);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("Código Establecimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel34, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(cmbZonaOficina, gridBagConstraints);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel36.setText("Zona:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel36, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(cmbTipoClienteOficina, gridBagConstraints);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelCaracteristicasGenerales1.add(jLabel39, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCaracteristicasGenerales1.add(jTextReferenciaDireccionEstablecimiento, gridBagConstraints);

        jToolBar1.setRollover(true);

        btnAgregarEstablecimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add2.png"))); // NOI18N
        btnAgregarEstablecimiento.setFocusable(false);
        btnAgregarEstablecimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarEstablecimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAgregarEstablecimiento);

        btnEditarEstablecimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/edit_icon.png"))); // NOI18N
        btnEditarEstablecimiento.setEnabled(false);
        btnEditarEstablecimiento.setFocusable(false);
        btnEditarEstablecimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarEstablecimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditarEstablecimiento);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 13;
        jPanelCaracteristicasGenerales1.add(jToolBar1, gridBagConstraints);

        jTabbedPane1.addTab("Establecimientos", jPanelCaracteristicasGenerales1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstablecimiento;
    private javax.swing.JButton btnEditarEstablecimiento;
    private javax.swing.JCheckBox chkContacto;
    private javax.swing.JCheckBox chkObligadoLlevarContabilidad;
    private javax.swing.JComboBox<GeneralEnumEstado> cmbEstado;
    private javax.swing.JComboBox<SriFormaPago> cmbFormaPagoDefecto;
    private javax.swing.JComboBox<Nacionalidad> cmbNacionalidad;
    private javax.swing.JComboBox<TipoEstablecimiento> cmbTipoCliente;
    private javax.swing.JComboBox<TipoEstablecimiento> cmbTipoClienteOficina;
    private javax.swing.JComboBox<TipoSucursalEnum> cmbTipoEstablecimiento;
    private javax.swing.JComboBox<OperadorNegocioEnum> cmbTipoOperador;
    private javax.swing.JComboBox<Zona> cmbZona;
    private javax.swing.JComboBox<Zona> cmbZonaOficina;
    private javax.swing.JComboBox<Persona.TipoIdentificacionEnum> jComboIdentificacion;
    private javax.swing.JComboBox<String> jComboTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCaracteristicasGenerales;
    private javax.swing.JPanel jPanelCaracteristicasGenerales1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextAreaDireccion;
    private javax.swing.JTextField jTextAreaDireccionEstablecimiento;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextCelularEstablecimiento;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextExtension;
    private javax.swing.JTextField jTextExtensionEstablecimiento;
    private javax.swing.JTextField jTextIdentificacion;
    private javax.swing.JTextField jTextNombreSocial;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextReferenciaDireccion;
    private javax.swing.JTextField jTextReferenciaDireccionEstablecimiento;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextTelefonoEstablecimiento;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEspacio;
    private javax.swing.JLabel lblEspacio11;
    private javax.swing.JLabel lblEspacio4;
    private javax.swing.JLabel lblEspacio5;
    private javax.swing.JLabel lblEspacio6;
    private javax.swing.JLabel lblEspacio7;
    private javax.swing.JLabel lblEspacio8;
    private javax.swing.JLabel lblEspacio9;
    private javax.swing.JLabel lblEspacioHorizontal;
    private javax.swing.JLabel lblEspacioVertical;
    private javax.swing.JLabel lblOligadoLlevarContabilidad;
    private javax.swing.JTable tblEstablecimientos;
    private javax.swing.JSpinner txtCodigoEstablecimiento;
    private javax.swing.JTextField txtCodigoPersonalizado;
    private javax.swing.JTextField txtCodigoPersonalizadoOficina;
    private javax.swing.JSpinner txtDiasCredito;
    private javax.swing.JSpinner txtDiasCreditoProveedor;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtNombreContacto;
    private javax.swing.JTextField txtNombreLegal;
    private javax.swing.JTextField txtNombreLegalEstablecimiento;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPorcentajeComision;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getjComboTipoCliente() {
        return jComboTipoCliente;
    }

    public void setjComboTipoCliente(JComboBox<String> jComboTipoCliente) {
        this.jComboTipoCliente = jComboTipoCliente;
    }

    public JPanel getjPanelCaracteristicasGenerales() {
        return jPanelCaracteristicasGenerales;
    }

    public void setjPanelCaracteristicasGenerales(JPanel jPanelCaracteristicasGenerales) {
        this.jPanelCaracteristicasGenerales = jPanelCaracteristicasGenerales;
    }

  
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=false ,min=0, expresionRegular = "[^\\n]*",nombre = "Direccion", expresionRegularMensaje = "No se permite la letra ñ, ni tildes")
    public JTextField getjTextAreaDireccion() {
        return jTextAreaDireccion;
    }

    public void setjTextAreaDireccion(JTextField jTextAreaDireccion) {
        this.jTextAreaDireccion = jTextAreaDireccion;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=false ,expresionRegular = "^[0][0-9]{9}$",nombre = "Celular", expresionRegularMensaje = "Ingrese un número de celular valido" )
    public JTextField getjTextCelular() {
        return jTextCelular;
    }

    public void setjTextCelular(JTextField jTextCelular) {
        this.jTextCelular = jTextCelular;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$", nombre = "Correo Electronico", expresionRegularMensaje = "Ingrese una dirección de correo valida" )
    public JTextField getjTextCorreo() {
        return jTextCorreo;
    }

    public void setjTextCorreo(JTextField jTextCorreo) {
        this.jTextCorreo = jTextCorreo;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=false , min=0 ,expresionRegular = "^[0-9]*$",nombre = "Extension")
    public JTextField getjTextExtension() {
        return jTextExtension;
    }

    public void setjTextExtension(JTextField jTextExtension) {
        this.jTextExtension = jTextExtension;
    }

    @CursorPorDefectoAnotacion   
    @CampoBuscarAnotacion
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true, personalizado ={"validarIdentificacionSegunOpcionEstablecida"} , min=0 ,max = 13,expresionRegular = "",nombre = NOMBRE_VALIDADOR_IDENTIFICACION)
    public JTextField getjTextIdentificacion() {
        return jTextIdentificacion;
    }

    public void setjTextIdentificacion(JTextField jTextIdentificacion) {
        this.jTextIdentificacion = jTextIdentificacion;
    }

    @CampoBuscarAnotacion
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=true , min=0 ,max = 100, expresionRegular ="[^\\n]*", nombre = "Nombre Social", expresionRegularMensaje = "No se permite la letra ñ, ni tildes" )
    public JTextField getjTextNombreSocial() {
        return jTextNombreSocial;
    }

    public void setjTextNombreSocial(JTextField jTextNombre) {
        this.jTextNombreSocial = jTextNombre;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido=false ,expresionRegular = "^[0][0-9]{8}$",nombre = "Telefono", expresionRegularMensaje = "Anteponga el código provincial")
    public JTextField getjTextTelefono() {
        return jTextTelefono;
    }

    public void setjTextTelefono(JTextField jTextTelefono) {
        this.jTextTelefono = jTextTelefono;
    }

    public JComboBox<Persona.TipoIdentificacionEnum> getjComboIdentificacion() {
        return jComboIdentificacion;
    }

    public void setjComboIdentificacion(JComboBox<Persona.TipoIdentificacionEnum> jComboIdentificacion) {
        this.jComboIdentificacion = jComboIdentificacion;
    }

    public JComboBox<GeneralEnumEstado> getCmbEstado() {
        return cmbEstado;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, min = 3, max = 200, expresionRegular = ExpresionRegular.textoSimpleSinNumeros, nombre = "Apellidos", expresionRegularMensaje = "No se permite la letra ñ, ni tildes")
    public JTextField getjTextApellidos() {
        return jTextApellidos;
    }

    public void setjTextApellidos(JTextField jTextApellidos) {
        this.jTextApellidos = jTextApellidos;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, min = 3, max = 200, expresionRegular = ExpresionRegular.textoSimpleSinNumeros, nombre = "Nombres", expresionRegularMensaje = "No se permite la letra ñ, ni tildes")
    public JTextField getjTextNombres() {
        return jTextNombres;
    }

    public void setjTextNombres(JTextField jTextNombres) {
        this.jTextNombres = jTextNombres;
    }

    public JComboBox<OperadorNegocioEnum> getCmbTipoOperador() {
        return cmbTipoOperador;
    }

    public void setCmbTipoOperador(JComboBox<OperadorNegocioEnum> cmbTipoOperador) {
        this.cmbTipoOperador = cmbTipoOperador;
    }

    public JComboBox<Nacionalidad> getCmbNacionalidad() {
        return cmbNacionalidad;
    }

    public void setCmbNacionalidad(JComboBox<Nacionalidad> cmbNacionalidad) {
        this.cmbNacionalidad = cmbNacionalidad;
    }

    public JComboBox<SriFormaPago> getCmbFormaPagoDefecto() {
        return cmbFormaPagoDefecto;
    }

    public void setCmbFormaPagoDefecto(JComboBox<SriFormaPago> cmbFormaPagoDefecto) {
        this.cmbFormaPagoDefecto = cmbFormaPagoDefecto;
    }

    public JCheckBox getChkObligadoLlevarContabilidad() {
        return chkObligadoLlevarContabilidad;
    }

    public void setChkObligadoLlevarContabilidad(JCheckBox chkObligadoLlevarContabilidad) {
        this.chkObligadoLlevarContabilidad = chkObligadoLlevarContabilidad;
    }

    public JLabel getLblOligadoLlevarContabilidad() {
        return lblOligadoLlevarContabilidad;
    }

    public void setLblOligadoLlevarContabilidad(JLabel lblOligadoLlevarContabilidad) {
        this.lblOligadoLlevarContabilidad = lblOligadoLlevarContabilidad;
    }

    public JTextField getTxtNombreLegal() {
        return txtNombreLegal;
    }

    public void setTxtNombreLegal(JTextField txtNombreLegal) {
        this.txtNombreLegal = txtNombreLegal;
    }

    public JCheckBox getChkContacto() {
        return chkContacto;
    }
    
    public JTextField getTxtPorcentajeComision() {
        return txtPorcentajeComision;
    }
    
    

    @ComponenteSecundarioAnotacion(nombreCategoria = "Mensajeria",visible = false)
    public ComponenteEnvioSmsPanel getPnlSms() {
        return pnlSms;
    }
    
    @ComponenteSecundarioAnotacion(nombreCategoria = "Correo Electrónico",visible = false)
    public ComponenteEnvioCorreoPanel getPnlCorreo() {
        return pnlCorreo;
    }

    public JSpinner getTxtDiasCredito() {
        return txtDiasCredito;
    }

    public JButton getBtnAgregarEstablecimiento() {
        return btnAgregarEstablecimiento;
    }

    public JComboBox<TipoSucursalEnum> getCmbTipoEstablecimiento() {
        return cmbTipoEstablecimiento;
    }

    public JSpinner getTxtCodigoEstablecimiento() {
        return txtCodigoEstablecimiento;
    }

    public JTextField getTxtNombreLegalEstablecimiento() {
        return txtNombreLegalEstablecimiento;
    }

    public JTextField getjTextAreaDireccionEstablecimiento() {
        return jTextAreaDireccionEstablecimiento;
    }

    public JTextField getjTextCelularEstablecimiento() {
        return jTextCelularEstablecimiento;
    }

    public JTextField getjTextExtensionEstablecimiento() {
        return jTextExtensionEstablecimiento;
    }

    public JTextField getjTextTelefonoEstablecimiento() {
        return jTextTelefonoEstablecimiento;
    }

    public JTable getTblEstablecimientos() {
        return tblEstablecimientos;
    }

    public JButton getBtnEditarEstablecimiento() {
        return btnEditarEstablecimiento;
    }

    @LimpiarAnotacion
    public JTextField getTxtNombreContacto() {
        return txtNombreContacto;
    }

    public JSpinner getTxtDiasCreditoProveedor() {
        return txtDiasCreditoProveedor;
    }

    public void setTxtDiasCreditoProveedor(JSpinner txtDiasCreditoProveedor) {
        this.txtDiasCreditoProveedor = txtDiasCreditoProveedor;
    }

    public JTextField getTxtCodigoPersonalizado() {
        return txtCodigoPersonalizado;
    }

    public void setTxtCodigoPersonalizado(JTextField txtCodigoPersonalizado) {
        this.txtCodigoPersonalizado = txtCodigoPersonalizado;
    }

    public JTextField getTxtCodigoPersonalizadoOficina() {
        return txtCodigoPersonalizadoOficina;
    }

    public void setTxtCodigoPersonalizadoOficina(JTextField txtCodigoPersonalizadoOficina) {
        this.txtCodigoPersonalizadoOficina = txtCodigoPersonalizadoOficina;
    }

    public JTextField getTxtLatitud() {
        return txtLatitud;
    }

    public void setTxtLatitud(JTextField txtLatitud) {
        this.txtLatitud = txtLatitud;
    }

    public JTextField getTxtLongitud() {
        return txtLongitud;
    }

    public void setTxtLongitud(JTextField txtLongitud) {
        this.txtLongitud = txtLongitud;
    }

    public JComboBox<Zona> getCmbZonaOficina() {
        return cmbZonaOficina;
    }

    public void setCmbZonaOficina(JComboBox<Zona> cmbZonaOficina) {
        this.cmbZonaOficina = cmbZonaOficina;
    }

    public JComboBox<Zona> getCmbZona() {
        return cmbZona;
    }

    public void setCmbZona(JComboBox<Zona> cmbZona) {
        this.cmbZona = cmbZona;
    }

    public JComboBox<TipoEstablecimiento> getCmbTipoClienteOficina() {
        return cmbTipoClienteOficina;
    }

    public void setCmbTipoClienteOficina(JComboBox<TipoEstablecimiento> cmbTipoClienteOficina) {
        this.cmbTipoClienteOficina = cmbTipoClienteOficina;
    }

    public JComboBox<TipoEstablecimiento> getCmbTipoCliente() {
        return cmbTipoCliente;
    }

    public void setCmbTipoCliente(JComboBox<TipoEstablecimiento> cmbTipoCliente) {
        this.cmbTipoCliente = cmbTipoCliente;
    }

    @LimpiarAnotacion
    public JTextField getjTextReferenciaDireccion() {
        return jTextReferenciaDireccion;
    }

    public void setjTextReferenciaDireccion(JTextField jTextReferenciaDireccion) {
        this.jTextReferenciaDireccion = jTextReferenciaDireccion;
    }

    public JTextField getjTextReferenciaDireccionEstablecimiento() {
        return jTextReferenciaDireccionEstablecimiento;
    }

    public void setjTextReferenciaDireccionEstablecimiento(JTextField jTextReferenciaDireccionEstablecimiento) {
        this.jTextReferenciaDireccionEstablecimiento = jTextReferenciaDireccionEstablecimiento;
    }

    @LimpiarAnotacion
    public JTextArea getTxtObservaciones() {
        return txtObservaciones;
    }

    public void setTxtObservaciones(JTextArea txtObservaciones) {
        this.txtObservaciones = txtObservaciones;
    }

    

    
}
