/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.crm.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vistas.core.TextFieldBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ButtonBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ComboBoxBinding;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.EnumSiNo;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @auhor
 */
public abstract class EjemploForm extends ControladorCodefacInterface {

    /**
     * Creates new form EjemploForm
     */
    public EjemploForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCampoTexto = new javax.swing.JTextField();
        btnEjemplo = new javax.swing.JButton();
        cmbSino = new javax.swing.JComboBox<>();
        BtnPrueba = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnEjemplo.setText("presionar");

        BtnPrueba.setText("BotonAuto");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbSino, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addComponent(btnEjemplo))))
                .addGap(39, 39, 39)
                .addComponent(btnSalir)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnPrueba)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BtnPrueba)
                .addGap(18, 18, 18)
                .addComponent(txtCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjemplo)
                    .addComponent(btnSalir))
                .addGap(54, 54, 54)
                .addComponent(cmbSino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPrueba;
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<EnumSiNo> cmbSino;
    private javax.swing.JTextField txtCampoTexto;
    // End of variables declaration//GEN-END:variables

    @TextFieldBinding(value = "saludo",editable = "visibleCampo")
    public JTextField getTxtCampoTexto() {
        return txtCampoTexto;
    }

    public void setTxtCampoTexto(JTextField txtCampoTexto) {
        this.txtCampoTexto = txtCampoTexto;
    }
    
    public JButton getBtnEjemplo() {
        return btnEjemplo;
    }

    public void setBtnEjemplo(JButton btnEjemplo) {
        this.btnEjemplo = btnEjemplo;
    }

    @ComboBoxBinding(source = "datosCombo",valueSelect = "datoSeleccionado")
    public JComboBox<EnumSiNo> getCmbSino() {
        return cmbSino;
    }

    public void setCmbSino(JComboBox<EnumSiNo> cmbSino) {
        this.cmbSino = cmbSino;
    }

    @ButtonBinding(actionListener = "listenerBotonEjemplo")
    public JButton getBtnPrueba() {
        return BtnPrueba;
    }

    public void setBtnPrueba(JButton BtnPrueba) {
        this.BtnPrueba = BtnPrueba;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    
    
    
    
}
