/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.crm.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ComboBoxBinding;
import ec.com.codesoft.codefaclite.corecodefaclite.ayuda.AyudaCodefacAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.util.LimpiarAnotacion;
import ec.com.codesoft.codefaclite.corecodefaclite.validation.ValidacionCodefacAnotacion;
import ec.com.codesoft.codefaclite.controlador.core.swing.GeneralPanelInterface;
import ec.com.codesoft.codefaclite.controlador.vista.crm.ProductoModelControlador.IvaOpcionEnum;
import ec.com.codesoft.codefaclite.controlador.vistas.converter.StringToBigDecimalConverter;
import ec.com.codesoft.codefaclite.controlador.vistas.core.TextFieldBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.CheckBoxBinding;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.CategoriaProducto;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.ImpuestoDetalle;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.MarcaProducto;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.academico.CatalogoProducto;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.EnumSiNo;
import ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.TipoProductoEnum;
import ec.com.codesoft.codefaclite.utilidades.validadores.ExpresionRegular;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public abstract class ProductoForm extends ControladorCodefacInterface {

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(min = 1,max = 300,requerido = true, expresionRegular = ExpresionRegular.textoSinSaltosLinea, nombre = "Nombre", expresionRegularMensaje = "No se permiten saltos de linea")
    @TextFieldBinding(value = "controlador.producto.nombre")
    public JTextField getTextNombre() {
        return textNombre;
    }

    public void setTextNombre(JTextField jTextNombre) {
        this.textNombre = jTextNombre;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+([.][0-9]+)?$", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    @TextFieldBinding(value = "controlador.producto.valorUnitario",converter = StringToBigDecimalConverter.class)
    public JTextField getTextValorUnitario() {
        return textValorUnitario;
    }

    public void setTextValorUnitario(JTextField jTextValorUnitario) {
        this.textValorUnitario = jTextValorUnitario;
    }


    /**
     * Creates new form ProductoForm
     */
    public ProductoForm() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator1 = new javax.swing.JSeparator();
        tabMenu = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoPersonalizado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textValorUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblEspacio2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboIva = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboIce = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        comboIrbpnr = new javax.swing.JComboBox<>();
        lblEspacio4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoProducto = new javax.swing.JComboBox<>();
        cmbIvaOpcionPrecioVentaPublico = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbManejaInventario = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        cmbGenerarCodigoBarras = new javax.swing.JComboBox<>();
        lblEspacioBlanco = new javax.swing.JLabel();
        chkGenerarCodigoAutomatico = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCaracteristica = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtImagenProducto = new javax.swing.JTextField();
        btnBuscarImagen = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoEAN = new javax.swing.JTextField();
        txtCodigoUPC = new javax.swing.JTextField();
        lblEspacio3 = new javax.swing.JLabel();
        txtPrecioTarjeta = new javax.swing.JTextField();
        txtPrecioDistribuidor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtPV5 = new javax.swing.JTextField();
        txtPV6 = new javax.swing.JTextField();
        txtPV4 = new javax.swing.JTextField();
        cmbMarca = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtAplicacionProducto = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosEnsamble = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtProductoEnsamble = new javax.swing.JTextField();
        btnBuscarProductoEnsamble = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadEnsamble = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblEspacio5 = new javax.swing.JLabel();
        lblEspacio1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAgregarEnsamble = new javax.swing.JButton();
        btnEditarEnsamble = new javax.swing.JButton();
        btnEliminarEnsamble = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cmbGarantia = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtCantidadMinima = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        lblEspacio6 = new javax.swing.JLabel();
        lblEspacio8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEspacio12 = new javax.swing.JLabel();
        chkTransportarGuiaRemision = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        chkOcultarDetalleVenta = new javax.swing.JCheckBox();
        lblEspacio23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPrecio1SinSubsidio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Producto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(200, 150));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Código Personalizado: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtCodigoPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPersonalizadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtCodigoPersonalizado, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel5, gridBagConstraints);

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(textNombre, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("P.Venta Publico (PV1):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel6, gridBagConstraints);

        textValorUnitario.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(textValorUnitario, gridBagConstraints);

        jLabel7.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.6;
        jPanel1.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(lblEspacio2, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Categoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbCategoriaProducto, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("IVA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(comboIva, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("ICE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(comboIce, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Generar Código Barras:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(comboIrbpnr, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        jPanel1.add(lblEspacio4, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbTipoProducto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbIvaOpcionPrecioVentaPublico, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Maneja Inventario?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbManejaInventario, gridBagConstraints);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("IRBPNR:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel29, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbGenerarCodigoBarras, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(lblEspacioBlanco, gridBagConstraints);

        chkGenerarCodigoAutomatico.setText("Generar automático");
        chkGenerarCodigoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGenerarCodigoAutomaticoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(chkGenerarCodigoAutomatico, gridBagConstraints);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        tabMenu.addTab("Info General", jPanel3);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Marca:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Caracteristicas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel17, gridBagConstraints);

        txtCaracteristica.setColumns(20);
        txtCaracteristica.setRows(3);
        jScrollPane2.setViewportView(txtCaracteristica);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jScrollPane2, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Aplicación del Producto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel18, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtImagenProducto, gridBagConstraints);

        btnBuscarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        btnBuscarImagen.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(btnBuscarImagen, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Observaciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel19, gridBagConstraints);

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(3);
        jScrollPane3.setViewportView(txtObservaciones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jScrollPane3, gridBagConstraints);

        jLabel24.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel5.add(jLabel24, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jLabel27, gridBagConstraints);

        jLabel34.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel5.add(jLabel34, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Código UPC: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel3, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Código EAN: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtCodigoEAN, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtCodigoUPC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel5.add(lblEspacio3, gridBagConstraints);

        txtPrecioTarjeta.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtPrecioTarjeta, gridBagConstraints);

        txtPrecioDistribuidor.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtPrecioDistribuidor, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("P.Venta Con Tarjeta (PV3):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel26, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("PV4:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel25, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("PV5:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel30, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("PV6:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel32, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("P.Venta Distribuidor (PV2):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel33, gridBagConstraints);

        txtPV5.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtPV5, gridBagConstraints);

        txtPV6.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtPV6, gridBagConstraints);

        txtPV4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtPV4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(cmbMarca, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Imagen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(txtAplicacionProducto, gridBagConstraints);

        tabMenu.addTab("Info Adicional", jPanel5);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setViewportView(tblDatosEnsamble);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Producto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jLabel9, gridBagConstraints);

        txtProductoEnsamble.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(txtProductoEnsamble, gridBagConstraints);

        btnBuscarProductoEnsamble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/Zoom.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(btnBuscarProductoEnsamble, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jLabel13, gridBagConstraints);

        txtCantidadEnsamble.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(txtCantidadEnsamble, gridBagConstraints);

        jLabel8.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        jPanel6.add(lblEspacio5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        jPanel6.add(lblEspacio1, gridBagConstraints);

        jToolBar1.setRollover(true);

        btnAgregarEnsamble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/add2.png"))); // NOI18N
        btnAgregarEnsamble.setFocusable(false);
        btnAgregarEnsamble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarEnsamble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAgregarEnsamble);

        btnEditarEnsamble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/pequenos/edit_icon.png"))); // NOI18N
        btnEditarEnsamble.setFocusable(false);
        btnEditarEnsamble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarEnsamble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditarEnsamble);

        btnEliminarEnsamble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cancel-ico.png"))); // NOI18N
        btnEliminarEnsamble.setFocusable(false);
        btnEliminarEnsamble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarEnsamble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarEnsamble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEnsambleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarEnsamble);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel6.add(jToolBar1, gridBagConstraints);

        tabMenu.addTab("Ensamble", jPanel6);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Garantia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel15, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(cmbGarantia, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Cantidad Minima:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel20, gridBagConstraints);

        txtCantidadMinima.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtCantidadMinima, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Ubicacion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel23, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(txtUbicacion, gridBagConstraints);

        jLabel31.setText("                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.2;
        jPanel4.add(jLabel31, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(lblEspacio6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel4.add(lblEspacio8, gridBagConstraints);

        tabMenu.addTab("Info Inventario", jPanel4);

        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(lblEspacio12, gridBagConstraints);

        chkTransportarGuiaRemision.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkTransportarGuiaRemision.setText("Transportar en Guía de Remisión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(chkTransportarGuiaRemision, gridBagConstraints);

        tabMenu.addTab("Transporte", jPanel2);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        chkOcultarDetalleVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkOcultarDetalleVenta.setText("Ocultar detalle en la venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(chkOcultarDetalleVenta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(lblEspacio23, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("PVP1 sin subsidio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(jLabel28, gridBagConstraints);

        txtPrecio1SinSubsidio.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel7.add(txtPrecio1SinSubsidio, gridBagConstraints);

        tabMenu.addTab("Otros", jPanel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(tabMenu, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
    }//GEN-LAST:event_textNombreActionPerformed

    private void btnEliminarEnsambleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEnsambleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEnsambleActionPerformed

    private void txtCodigoPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPersonalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPersonalizadoActionPerformed

    private void chkGenerarCodigoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGenerarCodigoAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkGenerarCodigoAutomaticoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEnsamble;
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnBuscarProductoEnsamble;
    private javax.swing.JButton btnEditarEnsamble;
    private javax.swing.JButton btnEliminarEnsamble;
    private javax.swing.JCheckBox chkGenerarCodigoAutomatico;
    private javax.swing.JCheckBox chkOcultarDetalleVenta;
    private javax.swing.JCheckBox chkTransportarGuiaRemision;
    private javax.swing.JComboBox<CategoriaProducto> cmbCategoriaProducto;
    private javax.swing.JComboBox<ec.com.codesoft.codefaclite.servidorinterfaz.enumerados.EnumSiNo> cmbGarantia;
    private javax.swing.JComboBox<EnumSiNo> cmbGenerarCodigoBarras;
    private javax.swing.JComboBox<IvaOpcionEnum> cmbIvaOpcionPrecioVentaPublico;
    private javax.swing.JComboBox<EnumSiNo> cmbManejaInventario;
    private javax.swing.JComboBox<MarcaProducto> cmbMarca;
    private javax.swing.JComboBox<TipoProductoEnum> cmbTipoProducto;
    private javax.swing.JComboBox<ImpuestoDetalle> comboIce;
    private javax.swing.JComboBox<ImpuestoDetalle> comboIrbpnr;
    private javax.swing.JComboBox<ImpuestoDetalle> comboIva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio12;
    private javax.swing.JLabel lblEspacio2;
    private javax.swing.JLabel lblEspacio23;
    private javax.swing.JLabel lblEspacio3;
    private javax.swing.JLabel lblEspacio4;
    private javax.swing.JLabel lblEspacio5;
    private javax.swing.JLabel lblEspacio6;
    private javax.swing.JLabel lblEspacio8;
    private javax.swing.JLabel lblEspacioBlanco;
    private javax.swing.JTabbedPane tabMenu;
    private javax.swing.JTable tblDatosEnsamble;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textValorUnitario;
    private javax.swing.JTextField txtAplicacionProducto;
    private javax.swing.JTextField txtCantidadEnsamble;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JTextArea txtCaracteristica;
    private javax.swing.JTextField txtCodigoEAN;
    private javax.swing.JTextField txtCodigoPersonalizado;
    private javax.swing.JTextField txtCodigoUPC;
    private javax.swing.JTextField txtImagenProducto;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPV4;
    private javax.swing.JTextField txtPV5;
    private javax.swing.JTextField txtPV6;
    private javax.swing.JTextField txtPrecio1SinSubsidio;
    private javax.swing.JTextField txtPrecioDistribuidor;
    private javax.swing.JTextField txtPrecioTarjeta;
    private javax.swing.JTextField txtProductoEnsamble;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Codigo EAN", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtCodigoEAN() {
        return txtCodigoEAN;
    }

    public void setTxtCodigoEAN(JTextField txtCodigoEAN) {
        this.txtCodigoEAN = txtCodigoEAN;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(max = 25,min=1, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Codigo Personalizado", expresionRegularMensaje = "No se permiten caracteres especiales")
    @TextFieldBinding(value = "controlador.producto.codigoPersonalizado")
    public JTextField getTxtCodigoPersonalizado() {
        return txtCodigoPersonalizado;
    }

    public void setTxtCodigoPersonalizado(JTextField txtCodigoPersonalizado) {
        this.txtCodigoPersonalizado = txtCodigoPersonalizado;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Codigo UPC", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtCodigoUPC() {
        return txtCodigoUPC;
    }

    public void setTxtCodigoUPC(JTextField txtCodigoUPC) {
        this.txtCodigoUPC = txtCodigoUPC;
    }

    @ComboBoxBinding(source ="controlador.garantiaList" , valueSelect ="controlador.producto.garantiaEnum" )
    public JComboBox<EnumSiNo> getCmbGarantia() {
        return cmbGarantia;
    }

    public void setCmbGarantia(JComboBox<EnumSiNo> cmbGarantia) {
        this.cmbGarantia = cmbGarantia;
    }

    //todo: revisar que esta devolviendo otro dato
    @LimpiarAnotacion
    public JTextField getTxtCantidad() {
        return txtCantidadEnsamble;
    }

    public void setTxtCantidad(JTextField txtCantidad) {
        this.txtCantidadEnsamble = txtCantidad;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+$", nombre = "Cantidad Minima", expresionRegularMensaje = "Solo numeros enteros")
    public JTextField getTxtCantidadMinima() {
        return txtCantidadMinima;
    }

    public void setTxtCantidadMinima(JTextField txtCantidadMinima) {
        this.txtCantidadMinima = txtCantidadMinima;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, nombre = "Caracteristica",max = 5000, expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextArea getTxtCaracteristica() {
        return txtCaracteristica;
    }

    public void setTxtCaracteristica(JTextArea txtCaracteristica) {
        this.txtCaracteristica = txtCaracteristica;
    }

    public JTextField getTxtImagenProducto() {
        return txtImagenProducto;
    }

    public void setTxtImagenProducto(JTextField txtImagenProducto) {
        this.txtImagenProducto = txtImagenProducto;
    }

    /*@LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Marca", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }*/

    @ComboBoxBinding(source ="controlador.marcaProductoList" , valueSelect ="controlador.producto.marcaProducto" )
    public JComboBox<MarcaProducto> getCmbMarca() {
        return cmbMarca;
    }

    public void setCmbMarca(JComboBox<MarcaProducto> cmbMarca) {
        this.cmbMarca = cmbMarca;
    }
    

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false,max =100 , expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Observaciones", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextArea getTxtObservaciones() {
        return txtObservaciones;
    }

    public void setTxtObservaciones(JTextArea txtObservaciones) {
        this.txtObservaciones = txtObservaciones;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+([.][0-9]+)?$", nombre = "Precio Distribuidor", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    public JTextField getTxtPrecioDistribuidor() {
        return txtPrecioDistribuidor;
    }

    public void setTxtPrecioDistribuidor(JTextField txtPrecioDistribuidor) {
        this.txtPrecioDistribuidor = txtPrecioDistribuidor;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+([.][0-9]+)?$", nombre = "Precio Distribuidor", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    public JTextField getTxtPrecioTarjeta() {
        return txtPrecioTarjeta;
    }

    public void setTxtPrecioTarjeta(JTextField txtPrecioTarjeta) {
        this.txtPrecioTarjeta = txtPrecioTarjeta;
    }

    @LimpiarAnotacion
    public JTextField getTxtProducto() {
        return txtProductoEnsamble;
    }

    public void setTxtProducto(JTextField txtProducto) {
        this.txtProductoEnsamble = txtProducto;
    }

    /*@LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+$", nombre = "Stock Inicial", expresionRegularMensaje = "Solo numeros enteros")
    public JTextField getTxtStockInicial() {
        return txtStockInicial;
    }

    public void setTxtStockInicial(JTextField txtStockInicial) {
        this.txtStockInicial = txtStockInicial;
    }*/

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = "^[a-zA-Z\\s0-9.\\_\\-]*$", nombre = "Ubicacion", expresionRegularMensaje = "No se permiten caracteres especiales")
    public JTextField getTxtUbicacion() {
        return txtUbicacion;
    }

    public void setTxtUbicacion(JTextField txtUbicacion) {
        this.txtUbicacion = txtUbicacion;
    }

    public JButton getBtnAgregarEnsamble() {
        return btnAgregarEnsamble;
    }

    public void setBtnAgregarEnsamble(JButton btnAgregarEnsamble) {
        this.btnAgregarEnsamble = btnAgregarEnsamble;
    }

    public JButton getBtnBuscarProductoEnsamble() {
        return btnBuscarProductoEnsamble;
    }

    public void setBtnBuscarProductoEnsamble(JButton btnBuscarProductoEnsamble) {
        this.btnBuscarProductoEnsamble = btnBuscarProductoEnsamble;
    }

    public JButton getBtnEditarEnsamble() {
        return btnEditarEnsamble;
    }

    public void setBtnEditarEnsamble(JButton btnEditarEnsamble) {
        this.btnEditarEnsamble = btnEditarEnsamble;
    }

    public JButton getBtnEliminarEnsamble() {
        return btnEliminarEnsamble;
    }

    public void setBtnEliminarEnsamble(JButton btnEliminarEnsamble) {
        this.btnEliminarEnsamble = btnEliminarEnsamble;
    }

    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = false, expresionRegular = ExpresionRegular.NUMEROS_DECIMALES, nombre = "Cantidad", expresionRegularMensaje = "Solo permite números")
    public JTextField getTxtCantidadEnsamble() {
        return txtCantidadEnsamble;
    }

    public void setTxtCantidadEnsamble(JTextField txtCantidadEnsamble) {
        this.txtCantidadEnsamble = txtCantidadEnsamble;
    }
    

    public JTable getTblDatosEnsamble() {
        return tblDatosEnsamble;
    }

    public void setTblDatosEnsamble(JTable tblDatosEnsamble) {
        this.tblDatosEnsamble = tblDatosEnsamble;
    }

    @LimpiarAnotacion
    public JTextField getTxtProductoEnsamble() {
        return txtProductoEnsamble;
    }

    public void setTxtProductoEnsamble(JTextField txtProductoEnsamble) {
        this.txtProductoEnsamble = txtProductoEnsamble;
    }

    @ComboBoxBinding(source = "controlador.categoriaProductosList",valueSelect = "controlador.categoriaSeleccionada")
    public JComboBox<CategoriaProducto> getCmbCategoriaProducto() {
        return cmbCategoriaProducto;
    }

    public void setCmbCategoriaProducto(JComboBox<CategoriaProducto> cmbCategoriaProducto) {
        this.cmbCategoriaProducto = cmbCategoriaProducto;
    }

    @ComboBoxBinding(source = "controlador.iceList",valueSelect = "controlador.iceSeleccionado")
    public JComboBox<ImpuestoDetalle> getComboIce() {
        return comboIce;
    }

    public void setComboIce(JComboBox<ImpuestoDetalle> comboIce) {
        this.comboIce = comboIce;
    }

    @ComboBoxBinding(source = "controlador.irbpnrList",valueSelect = "controlador.irbpnrSeleccionado")
    public JComboBox<ImpuestoDetalle> getComboIrbpnr() {
        return comboIrbpnr;
    }

    public void setComboIrbpnr(JComboBox<ImpuestoDetalle> comboIrbpnr) {
        this.comboIrbpnr = comboIrbpnr;
    }

    @ComboBoxBinding(source = "controlador.ivaList",valueSelect = "controlador.ivaSeleccionado")
    public JComboBox<ImpuestoDetalle> getComboIva() {
        return comboIva;
    }

    public void setComboIva(JComboBox<ImpuestoDetalle> comboIva) {
        this.comboIva = comboIva;
    }

    @ComboBoxBinding(source = "controlador.tipoProductosList",valueSelect = "controlador.producto.tipoProductoEnum")
    public JComboBox<TipoProductoEnum> getCmbTipoProducto() {
        return cmbTipoProducto;
    }

    public void setCmbTipoProducto(JComboBox<TipoProductoEnum> cmbTipoProducto) {
        this.cmbTipoProducto = cmbTipoProducto;
    }

    @ComboBoxBinding(source = "controlador.ivaOpcionList",valueSelect = "controlador.ivaOpcionSeleccionado")
    public JComboBox<IvaOpcionEnum> getCmbIvaOpcionPrecioVentaPublico() {
        return cmbIvaOpcionPrecioVentaPublico;
    }

    public void setCmbIvaOpcionPrecioVentaPublico(JComboBox<IvaOpcionEnum> cmbIvaOpcionPrecioVentaPublico) {
        this.cmbIvaOpcionPrecioVentaPublico = cmbIvaOpcionPrecioVentaPublico;
    }

    @ComboBoxBinding(source = "controlador.llevaInventarioList",valueSelect = "controlador.producto.manejarInventarioEnum")
    public JComboBox<EnumSiNo> getCmbManejaInventario() {
        return cmbManejaInventario;
    }

    public void setCmbManejaInventario(JComboBox<EnumSiNo> cmbManejaInventario) {
        this.cmbManejaInventario = cmbManejaInventario;
    }

    public JTabbedPane getTabMenu() {
        return tabMenu;
    }

    public void setTabMenu(JTabbedPane tabMenu) {
        this.tabMenu = tabMenu;
    }

    @ComboBoxBinding(source = "controlador.imprimirCodigoBarrasList",valueSelect = "controlador.producto.generarCodigoBarrasEnum")
    public JComboBox<EnumSiNo> getCmbGenerarCodigoBarras() {
        return cmbGenerarCodigoBarras;
    }

    public void setCmbGenerarCodigoBarras(JComboBox<EnumSiNo> cmbGenerarCodigoBarras) {
        this.cmbGenerarCodigoBarras = cmbGenerarCodigoBarras;
    }

    public JCheckBox getChkTransportarGuiaRemision() {
        return chkTransportarGuiaRemision;
    }

    public JCheckBox getChkOcultarDetalleVenta() {
        return chkOcultarDetalleVenta;
    }

    public void setChkOcultarDetalleVenta(JCheckBox chkOcultarDetalleVenta) {
        this.chkOcultarDetalleVenta = chkOcultarDetalleVenta;
    }

    public JTextField getTxtPrecio1SinSubsidio() {
        return txtPrecio1SinSubsidio;
    }

    public void setTxtPrecio1SinSubsidio(JTextField txtPrecio1SinSubsidio) {
        this.txtPrecio1SinSubsidio = txtPrecio1SinSubsidio;
    }

    
    @LimpiarAnotacion
    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+([.][0-9]+)?$", nombre = "PVP4", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    public JTextField getTxtPV4() {
        return txtPV4;
    }

    public void setTxtPV4(JTextField txtPV4) {
        this.txtPV4 = txtPV4;
    }

    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+([.][0-9]+)?$", nombre = "PVP5", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    public JTextField getTxtPV5() {
        return txtPV5;
    }

    public void setTxtPV5(JTextField txtPV5) {
        this.txtPV5 = txtPV5;
    }

    @ValidacionCodefacAnotacion(requerido = true, expresionRegular = "^[0-9]+([.][0-9]+)?$", nombre = "PVP6", expresionRegularMensaje = "Solo se permite numeros enteros y decimales")
    public JTextField getTxtPV6() {
        return txtPV6;
    }

    public void setTxtPV6(JTextField txtPV6) {
        this.txtPV6 = txtPV6;
    }

    @CheckBoxBinding(value = "controlador.generarCodigoAutomatico")
    public JCheckBox getChkGenerarCodigoAutomatico() {
        return chkGenerarCodigoAutomatico;
    }

    public void setChkGenerarCodigoAutomatico(JCheckBox chkGenerarCodigoAutomatico) {
        this.chkGenerarCodigoAutomatico = chkGenerarCodigoAutomatico;
    }

    public JTextField getTxtAplicacionProducto() {
        return txtAplicacionProducto;
    }

    public void setTxtAplicacionProducto(JTextField txtAplicacionProducto) {
        this.txtAplicacionProducto = txtAplicacionProducto;
    }

    
    
    

}
