/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.facturacion.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.controlador.vistas.core.DateComboBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.TableBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.TextFieldBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ButtonBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.CheckBoxBinding;
import ec.com.codesoft.codefaclite.controlador.vistas.core.components.ComboBoxBinding;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.PuntoEmision;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author CARLOS_CODESOFT
 */
public abstract class FacturaPedidoLotePanel extends ControladorCodefacInterface {

    /**
     * Creates new form GuiaRemisionLotePanel
     */
    public FacturaPedidoLotePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbFechaInicial = new org.jdesktop.swingx.JXDatePicker();
        cmbFechaFinal = new org.jdesktop.swingx.JXDatePicker();
        lblEspacio1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        lblEspacio123 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        btnBuscarVendedor = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        btnBuscarRuta = new javax.swing.JButton();
        chkSeleccionarTodosVendedores = new javax.swing.JCheckBox();
        chkSeleccionarTodasRutas = new javax.swing.JCheckBox();
        btnConsultar = new javax.swing.JButton();
        cmbSeleccionarTodo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblEspacio4747 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPuntoEmision = new javax.swing.JComboBox<>();
        lblEspacio124 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Fecha Final:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Vendedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbFechaInicial, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbFechaFinal, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblEspacio1, gridBagConstraints);

        jScrollPane1.setViewportView(tblDatos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblEspacio123, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Fecha Inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtVendedor.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtVendedor, gridBagConstraints);

        btnBuscarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(btnBuscarVendedor, gridBagConstraints);

        txtRuta.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtRuta, gridBagConstraints);

        btnBuscarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(btnBuscarRuta, gridBagConstraints);

        chkSeleccionarTodosVendedores.setSelected(true);
        chkSeleccionarTodosVendedores.setText("Todos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(chkSeleccionarTodosVendedores, gridBagConstraints);

        chkSeleccionarTodasRutas.setSelected(true);
        chkSeleccionarTodasRutas.setText("Todos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(chkSeleccionarTodasRutas, gridBagConstraints);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/find2-ico.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnConsultar, gridBagConstraints);

        cmbSeleccionarTodo.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        cmbSeleccionarTodo.setText("Seleccionar Todo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbSeleccionarTodo, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Adicionales Guía Remisión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Punto Emisión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(lblEspacio4747, gridBagConstraints);

        jLabel3.setText("001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(cmbPuntoEmision, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblEspacio124, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Establecimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Ruta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel7, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRuta;
    private javax.swing.JButton btnBuscarVendedor;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JCheckBox chkSeleccionarTodasRutas;
    private javax.swing.JCheckBox chkSeleccionarTodosVendedores;
    private org.jdesktop.swingx.JXDatePicker cmbFechaFinal;
    private org.jdesktop.swingx.JXDatePicker cmbFechaInicial;
    private javax.swing.JComboBox<ec.com.codesoft.codefaclite.servidorinterfaz.entity.PuntoEmision> cmbPuntoEmision;
    private javax.swing.JCheckBox cmbSeleccionarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio123;
    private javax.swing.JLabel lblEspacio124;
    private javax.swing.JLabel lblEspacio4747;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables

    @ButtonBinding(actionListener = "controlador.listenerBuscarVendedor")
    public JButton getBtnBuscarVendedor() {
        return btnBuscarVendedor;
    }

    public void setBtnBuscarVendedor(JButton btnBuscarVendedor) {
        this.btnBuscarVendedor = btnBuscarVendedor;
    }

    @ButtonBinding(actionListener = "controlador.listenerConsultarGuiasRemision")
    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    @DateComboBinding(value = "controlador.fechaFin")
    public JXDatePicker getCmbFechaFinal() {
        return cmbFechaFinal;
    }

    public void setCmbFechaFinal(JXDatePicker cmbFechaFinal) {
        this.cmbFechaFinal = cmbFechaFinal;
    }

    @DateComboBinding(value = "controlador.fechaInicial")
    public JXDatePicker getCmbFechaInicial() {
        return cmbFechaInicial;
    }

    public void setCmbFechaInicial(JXDatePicker cmbFechaInicial) {
        this.cmbFechaInicial = cmbFechaInicial;
    }

    @TableBinding(
            source = "controlador.ventasList",
            tableAddDataInterface = "tableBindingAddData",
            selectValue = "controlador.facturaSeleccionada",
            listSelected = "controlador.ventasSeleccionadasList",
            componenteCheckSelect = "cmbSeleccionarTodo",
            modeCheck = true,
            controlador = "controlador.tableBindingControlador")    
    public JTable getTblDatos() {
        return tblDatos;
    }

    public void setTblDatos(JTable tblDatos) {
        this.tblDatos = tblDatos;
    }


    @TextFieldBinding(value = "controlador.vendedorSeleccionado.nombresCompletos")
    public JTextField getTxtVendedor() {
        return txtVendedor;
    }

    public void setTxtVendedor(JTextField txtVendedor) {
        this.txtVendedor = txtVendedor;
    }

    public JCheckBox getCmbSeleccionarTodo() {
        return cmbSeleccionarTodo;
    }

    public void setCmbSeleccionarTodo(JCheckBox cmbSeleccionarTodo) {
        this.cmbSeleccionarTodo = cmbSeleccionarTodo;
    }
    
    @ButtonBinding(actionListener = "controlador.listenerBuscarRuta")
    public JButton getBtnBuscarRuta() {
        return btnBuscarRuta;
    }

    public void setBtnBuscarRuta(JButton btnBuscarRuta) {
        this.btnBuscarRuta = btnBuscarRuta;
    }
    
    @CheckBoxBinding(value = "controlador.seleccionTodosRuta",actionListener = "controlador.listenerCheckRutas")
    public JCheckBox getChkSeleccionarTodasRutas() {
        return chkSeleccionarTodasRutas;
    }

    public void setChkSeleccionarTodasRutas(JCheckBox chkSeleccionarTodasRutas) {
        this.chkSeleccionarTodasRutas = chkSeleccionarTodasRutas;
    }

    @CheckBoxBinding(value = "controlador.seleccionTodosVendedor",actionListener = "controlador.listenerCheckVendedores")
    public JCheckBox getChkSeleccionarTodosVendedores() {
        return chkSeleccionarTodosVendedores;
    }

    public void setChkSeleccionarTodosVendedores(JCheckBox chkSeleccionarTodosVendedores) {
        this.chkSeleccionarTodosVendedores = chkSeleccionarTodosVendedores;
    }

    @TextFieldBinding(value = "controlador.rutaSeleccionada.codigo")
    public JTextField getTxtRuta() {
        return txtRuta;
    }

    public void setTxtRuta(JTextField txtRuta) {
        this.txtRuta = txtRuta;
    }

    @ComboBoxBinding(source = "controlador.puntoEmisionList", valueSelect = "controlador.puntoEmisionSeleccionado" )
    public JComboBox<PuntoEmision> getCmbPuntoEmision() {
        return cmbPuntoEmision;
    }

    public void setCmbPuntoEmision(JComboBox<PuntoEmision> cmbPuntoEmision) {
        this.cmbPuntoEmision = cmbPuntoEmision;
    }

    
}
