/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.codesoft.codefaclite.facturacion.panel;

import ec.com.codesoft.codefaclite.controlador.aplicacion.ControladorCodefacInterface;
import ec.com.codesoft.codefaclite.facturacion.model.disenador.RepaintInterface;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.BandaComprobante;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.ComponenteComprobanteFisico;
import ec.com.codesoft.codefaclite.servidorinterfaz.entity.ComprobanteFisicoDisenio;
import java.awt.Graphics;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Carlos
 */
public abstract class FacturaDisenoPanel extends ControladorCodefacInterface {
    protected RepaintInterface repaintInterface;
    /**
     * Creates new form FacturaDisenoPanel
     */
    public FacturaDisenoPanel() {
        initComponents();        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTamanioLetra = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        jLabel3 = new javax.swing.JLabel();
        chkNegrita = new javax.swing.JCheckBox();
        cmbSeccion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnArriba = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        lblEspacio1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbDocumento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cmbComponente = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAnchoDocumento = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        txtAltoDocumento = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        txtAltoSeccion = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        txtX = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        txtY = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        txtAnchoComponente = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        txtAltoComponente = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        chkOculto = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        sliderZoom = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        txtPPP = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
                repaintInterface.repaint(g);
            }
        }
        ;

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Y:");
        panelContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 372, -1, -1));

        jLabel2.setText("X:");
        panelContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 342, -1, -1));
        panelContenedor.add(cmbTamanioLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 459, 185, -1));

        jLabel3.setText("Tamaño:");
        panelContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 462, -1, -1));

        chkNegrita.setBackground(new java.awt.Color(255, 255, 255));
        chkNegrita.setText("Negrita");
        chkNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNegritaActionPerformed(evt);
            }
        });
        panelContenedor.add(chkNegrita, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 489, 69, -1));

        panelContenedor.add(cmbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 133, 261, -1));
        panelContenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/up.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(btnArriba, gridBagConstraints);

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/right.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(btnDerecha, gridBagConstraints);

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/left.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(btnIzquierda, gridBagConstraints);

        btnDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/general/down.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(btnDown, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(lblEspacio1, gridBagConstraints);

        panelContenedor.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 249, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Documento");
        panelContenedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder("we"));
        panelContenedor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 291, -1));

        jLabel8.setText("PPP:");
        panelContenedor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel9.setText("Alto:");
        panelContenedor.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        panelContenedor.add(cmbDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 22, 261, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setText("División       ");
        panelContenedor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 111, -1, -1));
        panelContenedor.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 291, -1));

        jLabel10.setText("Alto:");
        panelContenedor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 163, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Componente");
        panelContenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 192, -1, -1));
        panelContenedor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 291, -1));

        panelContenedor.add(cmbComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 214, 261, -1));

        jLabel11.setText("Ancho:");
        panelContenedor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 402, -1, -1));

        jLabel12.setText("Alto:");
        panelContenedor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 432, -1, -1));
        panelContenedor.add(txtAnchoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, -1));
        panelContenedor.add(txtAltoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 50, 20));
        panelContenedor.add(txtAltoSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 165, 185, -1));
        panelContenedor.add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 339, 185, -1));
        panelContenedor.add(txtY, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 369, 185, -1));
        panelContenedor.add(txtAnchoComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 399, 185, -1));
        panelContenedor.add(txtAltoComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 429, 185, -1));

        chkOculto.setBackground(new java.awt.Color(255, 255, 255));
        chkOculto.setText("Oculto");
        panelContenedor.add(chkOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 489, -1, -1));
        panelContenedor.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 291, -1));

        jLabel14.setText("Zoom:");
        panelContenedor.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 558, -1, -1));

        sliderZoom.setBackground(new java.awt.Color(255, 255, 255));
        sliderZoom.setMinimum(30);
        sliderZoom.setValue(60);
        panelContenedor.add(sliderZoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 552, -1, -1));

        jLabel13.setText("Ancho:");
        panelContenedor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtPPP.setValue(300);
        panelContenedor.add(txtPPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));

        getContentPane().add(panelContenedor, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNegritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNegritaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JCheckBox chkNegrita;
    private javax.swing.JCheckBox chkOculto;
    private javax.swing.JComboBox<ComponenteComprobanteFisico> cmbComponente;
    private javax.swing.JComboBox<ComprobanteFisicoDisenio> cmbDocumento;
    private javax.swing.JComboBox<BandaComprobante> cmbSeccion;
    private javax.swing.JSpinner cmbTamanioLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JSlider sliderZoom;
    private javax.swing.JSpinner txtAltoComponente;
    private javax.swing.JSpinner txtAltoDocumento;
    private javax.swing.JSpinner txtAltoSeccion;
    private javax.swing.JSpinner txtAnchoComponente;
    private javax.swing.JSpinner txtAnchoDocumento;
    private javax.swing.JSpinner txtPPP;
    private javax.swing.JSpinner txtX;
    private javax.swing.JSpinner txtY;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnArriba() {
        return btnArriba;
    }

    public void setBtnArriba(JButton btnArriba) {
        this.btnArriba = btnArriba;
    }

    public JButton getBtnDerecha() {
        return btnDerecha;
    }

    public void setBtnDerecha(JButton btnDerecha) {
        this.btnDerecha = btnDerecha;
    }

    public JButton getBtnDown() {
        return btnDown;
    }

    public void setBtnDown(JButton btnDown) {
        this.btnDown = btnDown;
    }

    public JButton getBtnIzquierda() {
        return btnIzquierda;
    }

    public void setBtnIzquierda(JButton btnIzquierda) {
        this.btnIzquierda = btnIzquierda;
    }

    public JCheckBox getChkNegrita() {
        return chkNegrita;
    }

    public void setChkNegrita(JCheckBox chkNegrita) {
        this.chkNegrita = chkNegrita;
    }

    public JComboBox<ComponenteComprobanteFisico> getCmbComponente() {
        return cmbComponente;
    }

    public void setCmbComponente(JComboBox<ComponenteComprobanteFisico> cmbComponente) {
        this.cmbComponente = cmbComponente;
    }

    public JComboBox<ComprobanteFisicoDisenio> getCmbDocumento() {
        return cmbDocumento;
    }

    public void setCmbDocumento(JComboBox<ComprobanteFisicoDisenio> cmbDocumento) {
        this.cmbDocumento = cmbDocumento;
    }

    public JComboBox<BandaComprobante> getCmbSeccion() {
        return cmbSeccion;
    }

    public void setCmbSeccion(JComboBox<BandaComprobante> cmbSeccion) {
        this.cmbSeccion = cmbSeccion;
    }

    public JPanel getPanelContenedor() {
        return panelContenedor;
    }

    public void setPanelContenedor(JPanel panelContenedor) {
        this.panelContenedor = panelContenedor;
    }

    public JSpinner getTxtTamanio() {
        return cmbTamanioLetra;
    }

    public void setTxtTamanio(JSpinner txtTamanio) {
        this.cmbTamanioLetra = txtTamanio;
    }


    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JSpinner getCmbTamanioLetra() {
        return cmbTamanioLetra;
    }

    public void setCmbTamanioLetra(JSpinner cmbTamanioLetra) {
        this.cmbTamanioLetra = cmbTamanioLetra;
    }

    public JSpinner getTxtAltoComponente() {
        return txtAltoComponente;
    }

    public void setTxtAltoComponente(JSpinner txtAltoComponente) {
        this.txtAltoComponente = txtAltoComponente;
    }

    public JSpinner getTxtAltoDocumento() {
        return txtAltoDocumento;
    }

    public void setTxtAltoDocumento(JSpinner txtAltoDocumento) {
        this.txtAltoDocumento = txtAltoDocumento;
    }

    public JSpinner getTxtAltoSeccion() {
        return txtAltoSeccion;
    }

    public void setTxtAltoSeccion(JSpinner txtAltoSeccion) {
        this.txtAltoSeccion = txtAltoSeccion;
    }

    public JSpinner getTxtAnchoComponente() {
        return txtAnchoComponente;
    }

    public void setTxtAnchoComponente(JSpinner txtAnchoComponente) {
        this.txtAnchoComponente = txtAnchoComponente;
    }

    public JSpinner getTxtAnchoDocumento() {
        return txtAnchoDocumento;
    }

    public void setTxtAnchoDocumento(JSpinner txtAnchoDocumento) {
        this.txtAnchoDocumento = txtAnchoDocumento;
    }

    public JSpinner getTxtX() {
        return txtX;
    }

    public void setTxtX(JSpinner txtX) {
        this.txtX = txtX;
    }

    public JSpinner getTxtY() {
        return txtY;
    }

    public void setTxtY(JSpinner txtY) {
        this.txtY = txtY;
    }

    public JCheckBox getChkOculto() {
        return chkOculto;
    }

    public void setChkOculto(JCheckBox chkOculto) {
        this.chkOculto = chkOculto;
    }

    public JSlider getSliderZoom() {
        return sliderZoom;
    }

    public void setSliderZoom(JSlider sliderZoom) {
        this.sliderZoom = sliderZoom;
    }

    public JSpinner getTxtPPP() {
        return txtPPP;
    }

    public void setTxtPPP(JSpinner txtPPP) {
        this.txtPPP = txtPPP;
    }

    

    
    
    

    
}
