/**
 * Author:  PC
 * Created: 14-nov-2017
 */

INSERT INTO IMPUESTO (NOMBRE, CODIGO_SRI, DESCRIPCION) VALUES('IVA','2','Impuesto IVA');
INSERT INTO IMPUESTO (NOMBRE, CODIGO_SRI, DESCRIPCION) VALUES('ICE','3','Impuesto ICE');
INSERT INTO IMPUESTO (NOMBRE, CODIGO_SRI, DESCRIPCION) VALUES('IRBPNR','5','Impuesto IRBPNR');
