/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  PC
 * Created: 17-nov-2017
 */
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO,NOMBRE, PORCENTAJE,TARIFA, DESCRIPCION, FECHA_INICIO) VALUES (1,0,'IMPUESTO TARIFA 0%',0, 0,'IVA 0','2001-01-01');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO,NOMBRE, PORCENTAJE,TARIFA, DESCRIPCION, FECHA_INICIO) VALUES (1,2,'IVA 12%',0.12, 12,'IVA IMPUESTO AL VALOR AGREGADO 12%','2001-01-01');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO,NOMBRE, PORCENTAJE,TARIFA, DESCRIPCION, FECHA_INICIO, FECHA_FIN) VALUES (1,3,'IVA 14%',0.14, 14,'IVA IMPUESTO AL VALOR AGREGADO 14%','2016-06-01','2017-05-31');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2, 3023, 'Productos del tabaco y sucedáneos del tabaco', 15.0,'Productos del tabaco');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2, 3610, 'Perfumes y aguas de tocador', 20.0,'Perfumes y aguas de tocador');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2, 3620, 'Videojuegos', 35.0,'Videojuegos');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2, 3630, 'Armas de fuego', 30.0,'Armas de fuego');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2, 3640, 'Focos incandescentes', 10.0,'Focos incandescentes');
INSERT INTO IMPUESTO_DETALLE(ID_IMPUESTO, CODIGO, NOMBRE, PORCENTAJE, DESCRIPCION) VALUES (2, 3670, 'Cocinas, calefones y otros de uso doméstico a gas SRI ', 10.0,'Cocinas, calefones');


