INSERT INTO CLIENTE (TIPO_IDENTIFICACION,NACIONALIDAD_ID, SRI_FORMA_PAGO_ID, SRI_IDENTIFICACION_ID, NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, OBLIGADO_LLEVAR_CONTABILIDAD, ESTADO) 
	VALUES ('C',53, 1, 5, 'JUAN PROVEEDOR', 'PINARGO LOYA', 'P', 'JUAN PROVEEDOR PINARGO LOYA', NULL, '1010101010', 'CLIENTE', 'QUITO, SANGOLQUI', '022087044', '0', '0983528439', 'jcp_computer@hotmail.com', NULL, 'n', 'A');

INSERT INTO CLIENTE (TIPO_IDENTIFICACION,NACIONALIDAD_ID, SRI_FORMA_PAGO_ID, SRI_IDENTIFICACION_ID, NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, OBLIGADO_LLEVAR_CONTABILIDAD, ESTADO) 
	VALUES ('C',53, 1, 5, 'Xenos PROVEEDOR', 'Cotton
', 'P', 'PROVEEDOR DE PRUEBA', NULL, '1212121212', 'CLIENTE', 'QUITO, SANGOLQUI', '022087044', '0', '0983528439', 'demo1@hotmail.com', NULL, 'n', 'A');

INSERT INTO CLIENTE (TIPO_IDENTIFICACION,NACIONALIDAD_ID, SRI_FORMA_PAGO_ID, SRI_IDENTIFICACION_ID, NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, OBLIGADO_LLEVAR_CONTABILIDAD, ESTADO) 
	VALUES ('C',53, 1, 5, 'Emery PROVEEDOR', 'Weaver', 'P', 'PROVEEDOR DE PRUEBA', NULL, '1414141414', 'CLIENTE', 'QUITO, SANGOLQUI', '022087044', '0', '0983528439', 'demo3@hotmail.com', NULL, 'n', 'A');

INSERT INTO CLIENTE (TIPO_IDENTIFICACION,NACIONALIDAD_ID, SRI_FORMA_PAGO_ID, SRI_IDENTIFICACION_ID, NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, OBLIGADO_LLEVAR_CONTABILIDAD, ESTADO) 
	VALUES ('C',53, 1, 5, 'Salvador PROVEEDOR', 'Weaver', 'P', 'PROVEEDOR DE PRUEBA', NULL, '1616161616', 'CLIENTE', 'QUITO, SANGOLQUI', '022087044', '0', '0983528439', 'demo4@hotmail.com', NULL, 'n', 'A');

INSERT INTO CLIENTE (TIPO_IDENTIFICACION,NACIONALIDAD_ID, SRI_FORMA_PAGO_ID, SRI_IDENTIFICACION_ID, NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, OBLIGADO_LLEVAR_CONTABILIDAD, ESTADO) 
	VALUES ('C',53, 1, 5, 'Ira PROVEEDOR', 'Wilkins', 'P', 'PROVEEDOR DE PRUEBA', NULL, '1818181818', 'CLIENTE', 'QUITO, SANGOLQUI', '022087044', '0', '0983528439', 'demo5@hotmail.com', NULL, 'n', 'A');

INSERT INTO CLIENTE (TIPO_IDENTIFICACION,NACIONALIDAD_ID, SRI_FORMA_PAGO_ID, SRI_IDENTIFICACION_ID, NOMBRES, APELLIDOS, TIPO_OPERADOR, RAZON_SOCIAL, NOMBRE_LEGAL, IDENTIFICACION, TIPO_CLIENTE, DIRECCION, TELEFONO_CONVENCIONAL, EXTENSION_TELEFONO, TELEFONO_CELULAR, CORREO_ELECTRONICO, ACTIVIDAD_COMERCIAL, OBLIGADO_LLEVAR_CONTABILIDAD, ESTADO) 
	VALUES ('C',53, 1, 5, 'Rahim PROVEEDOR', 'Shaffer', 'P', 'PROVEEDOR DE PRUEBA', NULL, '1719468105', 'CLIENTE', 'QUITO, SANGOLQUI', '022087044', '0', '0983528439', 'demo6@hotmail.com', NULL, 'n', 'A');

INSERT INTO PRODUCTO (CATALOGO_PRODUCTO_ID, CODIGO_PERSONALIZADO, CODIGO_EAN, CODIGO_UPC, TIPO_PRODUCTO_COD, NOMBRE, VALOR_UNITARIO, ESTADO, UBICACION, GARANTIA, CANTIDAD_MINIMA, PRECIO_DISTRIBUIDOR, PRECIO_TARJETA, STOCK_INICIAL, MARCA, IMAGEN, CARACTERISTICAS, OBSERVACIONES) 
	VALUES (1, 'p002', 'e002', 'u002', 'p', 'mouse', 10.000, 'A', 'A', 'n', 0, 0.000, 0.000, 0, 'GENIUS', '', 'Ventilador con luces', 'Ninguna');

INSERT INTO PRODUCTO (CATALOGO_PRODUCTO_ID, CODIGO_PERSONALIZADO, CODIGO_EAN, CODIGO_UPC, TIPO_PRODUCTO_COD, NOMBRE, VALOR_UNITARIO, ESTADO, UBICACION, GARANTIA, CANTIDAD_MINIMA, PRECIO_DISTRIBUIDOR, PRECIO_TARJETA, STOCK_INICIAL, MARCA, IMAGEN, CARACTERISTICAS, OBSERVACIONES) 
	VALUES (1, 'p003', 'e003', 'u003', 'p', 'parlantes', 33.000, 'A', 'A', 'n', 0, 0.000, 0.000, 0, 'GENIUS', '', 'Ventilador con luces', 'Ninguna');

INSERT INTO PRODUCTO (CATALOGO_PRODUCTO_ID, CODIGO_PERSONALIZADO, CODIGO_EAN, CODIGO_UPC, TIPO_PRODUCTO_COD, NOMBRE, VALOR_UNITARIO, ESTADO, UBICACION, GARANTIA, CANTIDAD_MINIMA, PRECIO_DISTRIBUIDOR, PRECIO_TARJETA, STOCK_INICIAL, MARCA, IMAGEN, CARACTERISTICAS, OBSERVACIONES) 
	VALUES (1, 'p004', 'e004', 'u004', 'p', 'impresora', 285.000, 'A', 'A', 'n', 0, 0.000, 0.000, 0, 'epson', '', 'Ventilador con luces', 'Ninguna');

INSERT INTO PRODUCTO (CATALOGO_PRODUCTO_ID, CODIGO_PERSONALIZADO, CODIGO_EAN, CODIGO_UPC, TIPO_PRODUCTO_COD, NOMBRE, VALOR_UNITARIO, ESTADO, UBICACION, GARANTIA, CANTIDAD_MINIMA, PRECIO_DISTRIBUIDOR, PRECIO_TARJETA, STOCK_INICIAL, MARCA, IMAGEN, CARACTERISTICAS, OBSERVACIONES) 
	VALUES (1, 'p005', 'e005', 'u005', 'p', 'infocus', 500.000, 'A', 'A', 'n', 0, 0.000, 0.000, 0, 'SONY', '', 'Ventilador con luces', 'Ninguna');
